script/misc/GoerliUpgrade1.s.sol, script/output/M1_deployment_goerli_2023_3_23.json
- deployed the new contracts for the goerli upgrade
- need to update goerli deployment after upgrade
=> add new deployment script

src/contracts/strategies/StrategyBase.sol, src/test/Delegation.t.sol, src/test/DepositWithdraw.t.sol, src/test/EigenLayerTestHelper.t.sol, src/test/Pausable.t.sol, src/test/Whitelister.t.sol, src/test/unit/StrategyBaseUnit.t.sol
See commits. Primary change is to StrategyBase; everything else is to tests.
In reviewing you should specifically (in addition to normal review):
- read through and understand the OZ issue thread I've linked 
- verify that all of the comments I've added are sufficient explanation
- consider and understand the impact of the chosen values of `SHARES_OFFSET` and `BALANCE_OFFSET`
- comment if you think the chosen values are optimal. why / why not
=> Better mitigation of share inflation

src/test/Delegation.t.sol, src/test/EigenLayerDeployer.t.sol, src/test/EigenPod.t.sol, src/test/unit/DelayedWithdrawalRouterUnit.t.sol, src/test/unit/DelegationUnit.t.sol, src/test/unit/PausableUnit.t.sol, src/test/unit/PauserRegistryUnit.t.sol, src/test/unit/StrategyManagerUnit.t.sol
This PR is still a bit of a WIP.
It is OK to merge (all tests currently passing, pure improvement), but it still needs coverage added to the StrategyBase tests, at least.
=> Add event checks to unit tests

certora/harnesses/PausableHarness.sol, certora/specs/permissions/Pausable.spec, script/M1_Deploy.s.sol, script/M1_deploy.config.json, script/configs/M1_deploy_devnet.config.json, script/configs/M1_deploy_goerli.config.json, script/output/M1_MOCK_deployment_data.json, script/output/M1_deployment_goerli_2023_3_23.json, script/utils/ExistingDeploymentParser.sol, src/contracts/interfaces/IPauserRegistry.sol, src/contracts/permissions/Pausable.sol, src/contracts/permissions/PauserRegistry.sol, src/contracts/pods/EigenPodManager.sol, src/contracts/strategies/StrategyBaseTVLLimits.sol, src/test/DepositWithdraw.t.sol, src/test/EigenLayerDeployer.t.sol, src/test/EigenPod.t.sol, src/test/Pausable.t.sol, src/test/unit/DelayedWithdrawalRouterUnit.t.sol, src/test/unit/PausableUnit.t.sol, src/test/unit/PauserRegistryUnit.t.sol, src/test/unit/SlasherUnit.t.sol, src/test/unit/StrategyBaseTVLLimitsUnit.sol, src/test/unit/StrategyBaseUnit.t.sol, src/test/unit/StrategyManagerUnit.t.sol
- make pauser a mapping. role held by arbitrarily many addresses
- rename teamMultisig => operationsMultisig
- make TVL limits changeable by unpauser (previously this was permssioned to the pauser)
=> Pauser changes

src/contracts/interfaces/IPausable.sol, src/contracts/permissions/Pausable.sol, src/test/Pausable.t.sol, src/test/SigP/EigenPodManagerNEW.sol, src/test/mocks/EigenPodManagerMock.sol
allow the pauser registry to be settable by the unpauser
=> add setPauserRegistry and tests

script/configs/M1_deploy_mainnet.config.json, script/output/M1_deployment_mainnet_2023_6_9.json
=> Mainnet deploy

src/contracts/interfaces/IBLSPublicKeyCompendium.sol, src/contracts/interfaces/IBLSRegistry.sol, src/contracts/interfaces/IBeaconChainOracle.sol, src/contracts/interfaces/IDelayedService.sol, src/contracts/interfaces/IDelayedWithdrawalRouter.sol, src/contracts/interfaces/IDelegationManager.sol, src/contracts/interfaces/IDelegationTerms.sol, src/contracts/interfaces/IETHPOSDeposit.sol, src/contracts/interfaces/IEigenPod.sol, src/contracts/interfaces/IEigenPodManager.sol, src/contracts/interfaces/IPausable.sol, src/contracts/interfaces/IPauserRegistry.sol, src/contracts/interfaces/IPaymentManager.sol, src/contracts/interfaces/IQuorumRegistry.sol, src/contracts/interfaces/IRegistry.sol, src/contracts/interfaces/IServiceManager.sol, src/contracts/interfaces/ISlasher.sol, src/contracts/interfaces/IStrategy.sol, src/contracts/interfaces/IStrategyManager.sol, src/contracts/interfaces/IVoteWeigher.sol, src/contracts/interfaces/IWhitelister.sol
makes life easier for other people/projects importing the interfaces
=> laxer pragmas for interfaces

certora/specs/core/DelegationManager.spec
very minimal change, I haven't verified that rules are still correct, merely that they run
=> update spec with change to function

script/testing/M2_Deploy_From_Scratch.s.sol, script/testing/M2_deploy_from_scratch.config.json
Implementation of M2 deploy script for AVS team.
This is just the M1 script with the BLSPubkeyCompendium added and default config unpausing everything.
@samlaf does this work for you?
=> Impl m2 test deploy script

.github/workflows/test.yml
@ChaoticWalrus PR'd to your reduce build size branch because adding this check to the CI will help us from running into this issue in the future
=> Add Build Size Check Step to CI

certora/scripts/core/verifyDelegationManager.sh, certora/scripts/core/verifySlasher.sh, certora/scripts/core/verifyStrategyManager.sh, certora/scripts/libraries/verifyStructuredLinkedList.sh, certora/scripts/permissions/verifyPausable.sh, certora/scripts/strategies/verifyStrategyBase.sh, certora/specs/core/DelegationManager.spec, certora/specs/core/StrategyManager.spec, certora/specs/libraries/StructuredLinkedList.spec, src/contracts/core/DelegationManager.sol, src/test/unit/DelegationUnit.t.sol
PR should make property/rule failures fail the CI, as well as fixing existing failures.
=> Fix existing Certora specs

slither.config.json, src/contracts/core/DelegationManager.sol, src/contracts/core/StrategyManager.sol, src/contracts/core/StrategyManagerStorage.sol, src/contracts/interfaces/IDelegationManager.sol, src/contracts/libraries/BeaconChainProofs.sol, src/contracts/libraries/BytesArrayBitmaps.sol, src/contracts/middleware/example/ECDSARegistry.sol, src/contracts/middleware/example/HashThreshold.sol, src/contracts/pods/EigenPod.sol, src/contracts/strategies/StrategyBase.sol, src/contracts/strategies/StrategyBaseTVLLimits.sol
Variable name shadowing, disabling some detectors + a few minor nits.
=> Fix compiler and slither/solhint warnings

src/contracts/pods/EigenPodManager.sol
- add events for withdrawal indexing
=> add withdrawal events

certora/harnesses/BLSRegistryCoordinatorWithIndicesHarness.sol, certora/scripts/middleware/verifyBLSRegistryCoordinatorWithIndices.sh, certora/specs/middleware/BLSRegistryCoordinatorWithIndices.spec, src/contracts/interfaces/IRegistryCoordinator.sol, src/contracts/libraries/BitmapUtils.sol, src/contracts/middleware/BLSRegistryCoordinatorWithIndices.sol, src/test/mocks/RegistryCoordinatorMock.sol
Preliminary PR, just adds a couple rules.
@gpsanant Take a quick look and merge?
=> Add specs to multiquorums

src/contracts/libraries/BN254.sol, src/contracts/middleware/BLSSignatureChecker.sol, src/test/utils/BLSMockAVSDeployer.sol
[Implement: BLSSignatureChecker changes #949](https://github.com/Layr-Labs/eignlayr-contracts/issues/949?notification_referrer_id=NT_kwDOA1tA77M3NjgxODk2NDk1OjU2MzEyMDQ3&notifications_query=reason%3Aassign)
- check sorting of nonsigners
- sort nonsigners in tests
- update scalar_mul_tiny for use
=> BLSSignatureChecker Updates

src/contracts/core/DelegationManager.sol, src/test/unit/DelegationUnit.t.sol
also add a comment to the existing unit test for pausing new delegations
=> add flag for pausing undelegations and an associated unit test

src/contracts/core/DelegationManager.sol, src/contracts/interfaces/IEigenPod.sol, src/contracts/pods/EigenPod.sol, src/test/unit/DelegationUnit.t.sol
Deleting unused code and fixing comments.
See changes.
=> Minor eigen pods cleanup

src/contracts/core/Slasher.sol, src/contracts/core/StrategyManager.sol, src/contracts/interfaces/IBLSPublicKeyCompendium.sol, src/contracts/interfaces/IBLSRegistry.sol, src/contracts/interfaces/IDelayedWithdrawalRouter.sol, src/contracts/interfaces/IEigenPod.sol, src/contracts/interfaces/IEigenPodManager.sol, src/contracts/interfaces/IPausable.sol, src/contracts/interfaces/IPauserRegistry.sol, src/contracts/interfaces/IPaymentManager.sol, src/contracts/interfaces/ISlasher.sol, src/contracts/interfaces/IStrategyManager.sol, src/contracts/interfaces/IVoteWeigher.sol, src/contracts/middleware/BLSPublicKeyCompendium.sol, src/contracts/middleware/BLSRegistry.sol, src/contracts/middleware/PaymentManager.sol, src/contracts/middleware/VoteWeigherBase.sol, src/contracts/middleware/VoteWeigherBaseStorage.sol, src/contracts/permissions/Pausable.sol, src/contracts/permissions/PauserRegistry.sol, src/contracts/pods/DelayedWithdrawalRouter.sol, src/contracts/pods/EigenPod.sol, src/contracts/pods/EigenPodManager.sol, src/test/SigP/EigenPodManagerNEW.sol
Moved events in Slasher, SM, EPM, EP to interfaces
=> Moving Events to Interfaces

src/contracts/interfaces/IEigenPod.sol, src/contracts/libraries/BeaconChainProofs.sol, src/contracts/pods/EigenPod.sol, src/test/EigenPod.t.sol, src/test/mocks/EigenPodMock.sol
Move state root against block root proof outside validator and withdrawal proof loop
Created a new struct for stateRootProof
=> Move state root against block root proof outside loop

src/contracts/middleware/BLSPubkeyRegistry.sol, src/contracts/middleware/BLSPubkeyRegistryStorage.sol, src/contracts/middleware/IndexRegistry.sol, src/contracts/middleware/IndexRegistryStorage.sol, src/contracts/middleware/StakeRegistryStorage.sol, src/contracts/middleware/VoteWeigherBase.sol, src/contracts/middleware/VoteWeigherBaseStorage.sol
Also fixed StakeRegistry storage gap
=> Add upgradability to IndexRegistry and PubkeyRegistry

script/M1_Deploy.s.sol, script/testing/M2_Deploy_From_Scratch.s.sol, script/upgrade/GoerliM2Upgrade.s.sol, script/upgrade/GoerliUpgrade1.s.sol, src/contracts/interfaces/IEigenPod.sol, src/contracts/pods/EigenPod.sol, src/test/DepositWithdraw.t.sol, src/test/EigenLayerDeployer.t.sol, src/test/EigenPod.t.sol, src/test/mocks/EigenPodMock.sol, src/test/unit/EigenPodUnit.t.sol
=> Hexens EIG-14 Addressal

script/whitelist/Whitelister.sol, script/whitelist/delegationFaucet/DelegationFaucet.sol, src/contracts/core/DelegationManager.sol, src/contracts/interfaces/IDelegationFaucet.sol, src/contracts/interfaces/IDelegationManager.sol, src/contracts/interfaces/IWhitelister.sol, src/test/DelegationFaucet.t.sol, src/test/DepositWithdraw.t.sol, src/test/EigenLayerTestHelper.t.sol, src/test/mocks/DelegationManagerMock.sol, src/test/unit/DelegationUnit.t.sol
Adding ability to prove multiple queuedWithdrawals in a single function call
=> added multiple queuedwithdrawals function

src/contracts/interfaces/IEigenPodManager.sol, src/contracts/pods/EigenPodManager.sol, src/test/EigenPod.t.sol, src/test/mocks/EigenPodManagerMock.sol
=> Return the created EigenPod address from createPod

src/test/unit/DelegationUnit.t.sol
Failing unit test was the result of the staker address being fuzzed the same address as delegationApprover address and thus skipping the delegationApprover signature logic block. The following args were 
`args=[0x2a07706473244BC757E10F2a9E86fB532828afe3, 0x0000000000000000000000000000000000000000000000000000000000000443, 5175]]`
https://github.com/Layr-Labs/eigenlayer-contracts/actions/runs/7064381409/job/19232292907#step:5:195
=> Test: Fixing unit test for DelegationUnit

script/output/M1_deployment_goerli_2023_3_23.json, script/output/strategy/strategy_deployment_goerli_2023_12_4.json, script/strategy/DeployStrategies.s.sol
Deployed new strategies to goerli
Please go through checklist
=> Deploy goerli strategies

src/contracts/libraries/BeaconChainProofs.sol
Fixed comment describing withdrawal index calculation
=> Fixed comments

src/contracts/libraries/BeaconChainProofs.sol
Remove unused constants in BeaconChainProofs.sol
=> EGN3-07: Beaconchainproofs.sol cleanup

script/deploy/mainnet/M2_Mainnet_Upgrade.s.sol, script/utils/ExistingDeploymentParser.sol, script/utils/Multisend.sol, script/utils/TimelockEncoding.sol, script/utils/TxEncodingInterfaces.sol
this PR also imports various tx-queuing-related utils
=> feat: add upgrade queue test

src/contracts/core/Slasher.sol
the max slashing rate should simply be the max bips opted in by the operator
an AVS will slash the maximum in a worst case scenario. further slashing conditions and slashing parameterization is in scope for a future release
=> get rid of max slashing rate

src/contracts/core/AVSDirectory.sol, src/contracts/interfaces/IAVSDirectory.sol, src/test/events/IAVSDirectoryEvents.sol, src/test/unit/AVSDirectoryUnit.t.sol
Bring back operator set struct per discussion in slack w/Bowen. Has consistency with slashing release.
=> feat: operator set struct

src/contracts/interfaces/IStrategy.sol, src/contracts/strategies/StrategyBase.sol, src/test/unit/StrategyBaseUnit.t.sol
- Emits in deposits/withdrawals
- Adds natspec
- Adds decimal emit event
=> feat: emit exchange rate on deposits/withdrawals

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/install.sh, .github/workflows/format.yml, .vscode/tasks.json, Dockerfile, certora/scripts/core/verifyDelegationManager.sh, certora/scripts/core/verifyStrategyManager.sh, certora/scripts/libraries/verifyStructuredLinkedList.sh, certora/scripts/permissions/verifyPausable.sh, certora/scripts/pods/verifyEigenPod.sh, certora/scripts/pods/verifyEigenPodManager.sh, certora/scripts/strategies/verifyStrategyBase.sh, certora/specs/core/DelegationManager.spec, certora/specs/pods/EigenPod.spec, certora/specs/pods/EigenPodManager.spec, package-lock.json, package.json
1. require solhint in GitHub format action
2. include npm in dev container
3. add vscode tasks.json for local build
4. format action is now lint and check format action
=> Task: require solhint as part of continuous integration

script/configs/devnet/deploy_from_scratch.anvil.config.json, script/configs/devnet/deploy_from_scratch.holesky.config.json, script/deploy/devnet/Deploy_From_Scratch.s.sol, script/deploy/devnet/Upgrade.s.sol, script/deploy/holesky/M2_Deploy_From_Scratch.s.sol, src/contracts/core/AVSDirectory.sol, src/contracts/core/DelegationManager.sol, src/contracts/core/DelegationManagerStorage.sol, src/contracts/interfaces/IAVSDirectory.sol, src/test/integration/IntegrationDeployer.t.sol, src/test/mocks/AVSDirectoryMock.sol, src/test/unit/AVSDirectoryUnit.t.sol
- Adding deployment scripts
- Adding `getSlashableMagnitudes` method to get slashable magnitude for given operator and set of strategies 
- Update all scripts to take avsDirectory as input
=> chore: some changes for making deployments

script/configs/local/deploy_from_scratch.anvil.config.json, script/deploy/local/Deploy_From_Scratch.s.sol, src/contracts/core/AllocationManager.sol, src/contracts/interfaces/IAllocationManager.sol
- add view methods
- fix scripts
=> feat: add pending allocations methods

pkg/bindings/DelegationManagerStorage/binding.go, pkg/bindings/EigenPodManagerStorage/binding.go, pkg/bindings/IDelegationManager/binding.go, pkg/bindings/IEigenPodManager/binding.go, pkg/bindings/IStrategyManager/binding.go, pkg/bindings/StrategyManager/binding.go, pkg/bindings/StrategyManagerStorage/binding.go, script/configs/devnet/deploy_from_scratch.anvil.config.json, script/configs/devnet/deploy_from_scratch.holesky.config.json, script/deploy/devnet/Upgrade.s.sol, script/deploy/holesky/M2_Deploy_From_Scratch.s.sol, script/deploy/local/Deploy_From_Scratch.s.sol, script/deploy/mainnet/Deploy_Strategy_Factory.s.sol, script/utils/ExistingDeploymentParser.sol, src/contracts/core/AllocationManager.sol, src/contracts/core/AllocationManagerStorage.sol, src/contracts/core/DelegationManager.sol, src/contracts/core/DelegationManagerStorage.sol, src/contracts/core/StrategyManager.sol, src/contracts/core/StrategyManagerStorage.sol, src/contracts/interfaces/IAllocationManager.sol, src/contracts/interfaces/IDelegationManager.sol, src/contracts/interfaces/IStrategyFactory.sol, src/contracts/libraries/SlashingConstants.sol, src/test/integration/IntegrationDeployer.t.sol, src/test/integration/users/User.t.sol, src/test/mocks/DelegationManagerMock.sol, src/test/unit/AVSDirectoryUnit.t.sol, src/test/unit/StrategyManagerUnit.t.sol
Makes the allocation delay configurable and immutable by fixing git setup on #740
=> add allocation delay

docs/storage-report/AVSDirectory.md, docs/storage-report/AVSDirectoryStorage.md, docs/storage-report/BackingEigen.md, docs/storage-report/DelegationManager.md, docs/storage-report/DelegationManagerStorage.md, docs/storage-report/Eigen.md, docs/storage-report/EigenPod.md, docs/storage-report/EigenPodManager.md, docs/storage-report/EigenPodManagerStorage.md, docs/storage-report/EigenPodPausingConstants.md, docs/storage-report/EigenPodStorage.md, docs/storage-report/EigenStrategy.md, docs/storage-report/Pausable.md, docs/storage-report/PauserRegistry.md, docs/storage-report/RewardsCoordinator.md, docs/storage-report/RewardsCoordinatorStorage.md, docs/storage-report/Slasher.md, docs/storage-report/StrategyBase.md, docs/storage-report/StrategyBaseTVLLimits.md, docs/storage-report/StrategyFactory.md, docs/storage-report/StrategyFactoryStorage.md, docs/storage-report/StrategyManager.md, docs/storage-report/StrategyManagerStorage.md, docs/storage-report/UpgradeableSignatureCheckingUtils.md
Dummy PR to trigger new storage report workflow, only merge if you want the generated report in `docs/`.
=> feat: storage report

src/contracts/core/StakeRootCompendium.sol
Allows OperatorSets to rejoin without clearing previous strategiesAndMultipliers. This means OperatorSets must also be allowed to modify their strategiesAndMultipliers before rejoining.
I've also updated the comments about front running when claiming the penalty for kicking out operator sets
=> feat: simplify rejoin

src/contracts/core/AllocationManager.sol, src/contracts/interfaces/IAllocationManager.sol
- remove ordering check since we only have 1 alloc or 1 dealloc
=> fix: patch ordering

src/contracts/core/AllocationManager.sol, src/contracts/interfaces/IAllocationManager.sol
- remove numToComplete and add max
=> fix: patch getallocatable mag

src/contracts/core/RewardsCoordinator.sol, src/contracts/interfaces/IRewardsCoordinator.sol, src/test/unit/RewardsCoordinatorUnit.t.sol
Changes:
- adds`processClaims(claims)`.
=> feat: process multiple claims

src/contracts/core/AllocationManager.sol, src/contracts/interfaces/IAllocationManager.sol
various comment and code cleanup
- fixed a bug on line 219
@shrimalmadhur can you verify these view functions aren't needed?
=> Am cleanup

.gitattributes
https://github.com/github-linguist/linguist/blob/main/docs/overrides.md#generated-code
=> chore: ignore bindings in pull requests

src/contracts/core/AllocationManager.sol, src/contracts/core/DelegationManager.sol, src/contracts/core/DelegationManagerStorage.sol, src/contracts/core/StrategyManager.sol, src/contracts/core/StrategyManagerStorage.sol, src/contracts/interfaces/IDelegationManager.sol, src/contracts/interfaces/IEigenPodManager.sol, src/contracts/interfaces/IShareManager.sol, src/contracts/interfaces/IStrategyManager.sol, src/contracts/libraries/SlashingLib.sol, src/contracts/pods/EigenPodManager.sol, src/contracts/pods/EigenPodManagerStorage.sol, src/contracts/strategies/StrategyBase.sol
Reverts Layr-Labs/eigenlayer-contracts#788
=> Revert "DM Cleanup"

src/contracts/core/AllocationManager.sol, src/contracts/core/DelegationManager.sol, src/contracts/core/DelegationManagerStorage.sol, src/contracts/core/StrategyManager.sol, src/contracts/core/StrategyManagerStorage.sol, src/contracts/interfaces/IDelegationManager.sol, src/contracts/interfaces/IEigenPodManager.sol, src/contracts/interfaces/IShareManager.sol, src/contracts/interfaces/IStrategyManager.sol, src/contracts/libraries/SlashingLib.sol, src/contracts/pods/EigenPodManager.sol, src/contracts/pods/EigenPodManagerStorage.sol, src/contracts/strategies/StrategyBase.sol
=> fix: compiles

src/contracts/core/AllocationManager.sol, src/contracts/interfaces/IAllocationManager.sol, src/test/mocks/AVSDirectoryMock.sol, src/test/unit/AllocationManagerUnit.t.sol
- Tests revert cases
- Tests a basic allocation & then slash
=> Slashing: Basic Allocation Manager Happy Path Tests

.github/workflows/coverage.yml
Has the same name as running tests.
=> Fix: CI Coverage Name

script/deploy/holesky/upgrade_preprod_rewardsCoordinator.s.sol
=> fix: fixed compile

script/admin/mainnet/Mainnet_Unpause_Deposits.s.sol, script/deploy/holesky/Preprod_Upgrade_bEIGEN_and_EIGEN.s.sol, script/deploy/holesky/bEIGEN_and_EIGEN_upgrade.s.sol, script/deploy/holesky/upgrade_preprod_rewardsCoordinator.s.sol, script/deploy/local/Deploy_From_Scratch.s.sol, script/deploy/mainnet/EIGEN_timelock_reduction.s.sol, script/deploy/mainnet/EIGEN_upgrade.s.sol, script/deploy/mainnet/EigenPod_Minor_Upgrade_Deploy.s.sol, script/deploy/mainnet/M2_Mainnet_Upgrade.s.sol, script/deploy/mainnet/bEIGEN_timelock_reduction.s.sol, script/deploy/mainnet/bEIGEN_upgrade.s.sol, script/whitelist/delegationFaucet/DeployDelegationFaucet.sol, src/test/EigenLayerDeployer.t.sol, src/test/integration/IntegrationDeployer.t.sol, src/test/integration/TimeMachine.t.sol, src/test/integration/mocks/BeaconChainMock.t.sol, src/test/integration/users/User.t.sol, src/test/mocks/Reenterer.sol, src/test/unit/PausableUnit.t.sol, src/test/unit/PauserRegistryUnit.t.sol, src/test/unit/StrategyBaseUnit.t.sol, src/test/utils/EigenLayerUnitTestBase.sol, src/test/utils/EigenPodUser.t.sol
=> Fix: Get Dev to Compile

src/contracts/core/DelegationManager.sol, src/contracts/interfaces/IDelegationManager.sol, src/test/unit/DelegationUnit.t.sol
added the shares here for easier indexing.
not very clean though...
=> feat: add shares to queue event

src/contracts/core/AVSDirectory.sol, src/contracts/core/AllocationManager.sol, src/contracts/core/DelegationManager.sol, src/contracts/core/StrategyManager.sol, src/contracts/interfaces/IAVSDirectory.sol, src/contracts/interfaces/IAllocationManager.sol, src/contracts/interfaces/IDelegationManager.sol, src/contracts/interfaces/ISignatureUtils.sol, src/contracts/interfaces/IStrategyManager.sol, src/contracts/libraries/SlashingLib.sol, src/contracts/mixins/SignatureUtils.sol, src/test/Delegation.t.sol, src/test/unit/AVSDirectoryUnit.t.sol, src/test/unit/DelegationUnit.t.sol, src/test/unit/StrategyManagerUnit.t.sol
Note: one test failing due to rounding issues.
@8sunyuan will correct in followup PR
=> feat: small delegation refactors

src/test/unit/DelegationUnit.t.sol
=> fix: flaky UAM fuzz test

script/releases/v0.5.2-rewardsv2/upgrade.json
=> chore: fix semver constraint on rewardsv2

script/releases/EigenLabsUpgrade.s.sol
per: https://github.com/Layr-Labs/eigenlayer-contracts-metadata/pull/6
- `zeus test --env preprod script/releases/v0.5.1-rewardsv2/*.s.sol`
- `zeus test --env preprod script/releases/v0.5.2-rewardsv2/*.s.sol`
=> chore: fix zeus environment

script/releases/v0.5.3-rewardsv2/1-eoa.s.sol, script/releases/v0.5.3-rewardsv2/2-multisig.s.sol, script/releases/v0.5.3-rewardsv2/3-multisig.s.sol, script/releases/v0.5.3-rewardsv2/upgrade.json
Deploying new RewardsCoordinator implementation with operator split activation delay lock.
=> fix: patch operator split lock upgrade

docs/core/RewardsCoordinator.md
Adding Rewards v2 into the existing documentation for the `RewardsCoordinator`
=> docs: rewards v2

script/releases/v1.0.0-slashing/cleanup/script.go, script/releases/v1.0.0-slashing/cleanup/start.sh
patches cleanup step for slashing upgrade
=> fix: patch

script/configs/mainnet.json, script/utils/ExistingDeploymentParser.sol, src/contracts/mixins/SignatureUtils.sol, src/test/integration/IntegrationBase.t.sol, src/test/integration/IntegrationDeployer.t.sol, src/test/integration/tests/Deposit_Delegate_Allocate.t.sol, src/test/integration/users/User.t.sol, src/test/unit/mixins/SignatureUtilsUnit.t.sol
Duplicate of #979, h/t to @davidberiro for pointing this out.
=> fix: `SignatureUtils` construction

script/releases/v0.5.4-rewardsv2/1-eoa.s.sol, script/releases/v0.5.4-rewardsv2/2-multisig.s.sol, script/releases/v0.5.4-rewardsv2/3-multisig.s.sol, script/releases/v0.5.4-rewardsv2/upgrade.json
Deploying new RewardsCoordinator implementation with default split frontrun fix.
=> fix: default split frontrun patch upgrade

script/releases/v1.1.0-slashing/1-eoa.s.sol, script/releases/v1.1.0-slashing/2-multisig.s.sol, script/releases/v1.1.0-slashing/3-execute.s.sol, script/releases/v1.1.0-slashing/upgrade.json
We need to upgrade the `RewardsCoordinator` for the Rewards v2.1 release.
v1.1.0 zeus release
**Result:**
Functioning zeus script with tests
=> chore: rewards v2.1 zeus script

docs/core/RewardsCoordinator.md
=> docs: updated rewards v2.1 docs

.github/workflows/foundry.yml, src/test/unit/libraries/BytesLibUnit.t.sol, src/test/unit/libraries/SnapshotsUnit.t.sol
Improving test coverage to meet the 90% requirement and ensure reliability.  
- Added missing tests for libraries (`Snapshots`, `BytesLib`. 
**Result:**  
Increased coverage, passing checks, and improved test reliability.
=> test: improve coverage

script/releases/v1.1.0-slashing/upgrade.json
=> fix: zeus upgrade name

src/test/integration/mocks/BeaconChainMock.t.sol, src/test/integration/mocks/BeaconChainMock_Pectra.t.sol, src/test/integration/tests/upgrade/Prooftra.t.sol, src/test/unit/EigenPodUnit.t.sol, src/test/utils/EigenPodUser.t.sol
=> feat: beacon chain mock

docs/core/accounting/SharesAccountingEdgeCases.md
Update docs with clarification/justification on rounding behaviors for stakers/operators.
Updated docs/SharesAccountingEdgeCases.md
**Result:**
Updated docs based on audit feedback and clarity for audit comp.
=> docs: rounding for stakers/operators

.github/labeler.yml, .github/workflows/automation.yml
Automate PR labeling to improve workflow efficiency and consistency.
- Added GitHub Actions workflow using actions/labeler@v5
- Created configuration for all existing labels based on file paths and branch names
**Result:**
PRs will be automatically labeled based on changes and branch names, reducing manual work and improving organization.
=> feat: add pull request labeler to ci pipeline

.github/labeler.yml
Enhance the Labeler CI automation to improve accuracy and efficiency.
- Ensure `src/contracts/` changes are always labeled `Enhancement`.
- Any branches with `slashing` in the name are labeled `Slashing Release`.
- `test/slashing-integration-testing` should now properly trigger a `Slashing Release` label.
**Result:**
Labeler CI automation should be more streamlined, and less error prone.
=> chore: improve labeler config

.github/workflows/foundry.yml
Path filter in CI has been problematic, and doesn't provide much benefit.
- Removed path filtering from `Foundry.yml`.
**Result:**
Nobody's blocked.
=> chore: disable ci path filtering

docs/README.md
Update docs to upcoming semver version: `v1.3.0`
=> chore: update doc version

.github/workflows/certora-prover.yml, certora/specs/core/DelegationManager.spec
Currently Certora workflow is intensive but we also want to make use of the properties and maintain on a more frequent cadence.
Updating the certora-prover workflow to run when
1. `feat/*` PRs are merged into `dev`
2. Any pushes to a `certora/*` named branch
3. biweekly cron schedule (can increase/reduce frequency)
4. manually scheduled run
**Result:**
Added Certora FV to CI
=> chore: certora workflow update

docs/core/RewardsCoordinator.md
Rewards calculation was outdated. We need to update it.
Updated Rewards calculation link
**Result:**
Correct link
=> docs: update rewards calculation link

src/contracts/token/BackingEigen.sol, src/test/token/EigenWrapping.t.sol, src/test/token/bEIGEN.t.sol
per ELIP-5, remove transfer restriction function from backing eigen
remove transfer restriction function from backing eigen
**Result:**
remove transfer restriction function from backing eigen
=> feat: remove transfer restriction function from backing eigen

.github/workflows/foundry.yml
per eigengit, main will be the new canonical branch
change push branch from dev to main
**Result:**
ci will be run on PRs against main
=> ci: change push branch to main

.github/workflows/foundry.yml
=> ci: change workflow target

.github/workflows/foundry.yml
remove holesky rpc since it's not used anywhere
remove holesky rpc
**Result:**
remove holesky rpc
=> ci: remove holesky rpc

.github/workflows/foundry.yml
currently tests run on doc changes which is unnecessary
ignore tests on doc changes 
**Result:**
tests not on doc changes
=> ci: not run tests on  doc changes

CONTRIBUTING.md
rewrite CONTRIBUTING.md to include new development workflow
rewrite CONTRIBUTING.md
**Result:**
rewrite CONTRIBUTING.md
=> docs: rewrite CONTRIBUTING.md

MAINTENANCE.md
author MAINTENANCE.md with environment network definitions and development workflow
author MAINTENANCE.md
**Result:**
author MAINTENANCE.md
=> docs: author MAINTENANCE.md with environment network definitions and development workflow

CONTRIBUTING.md
add more detailed doc
add how to sync from remote repo to CONTRIBUTING.md
**Result:**
add how to sync from remote repo to CONTRIBUTING.md
=> docs: add how to sync from remote repo to CONTRIBUTING.md

README.md
=> docs: update branch model in README

MAINTENANCE.md
complete MAINTENANCE.md and clarify maintainers responsibility
complete MAINTENANCE.md
**Result:**
clarify maintainers responsibility
=> docs: complete MAINTENANCE.md and clarify maintainers responsibility

CONTRIBUTING.md, README.md
simplify readme and make it clear to readers
simplify readme and consolidate with CONTRIBUTING.md
**Result:**
simplify readme and consolidate with CONTRIBUTING.md
=> docs: simplify readme and consolidate with CONTRIBUTING.md

README.md
improve readability and searchbility with tabs for deployment contracts
change deployment contracts to use tabs
**Result:**
improved readability and searchbility
=> docs: improve readability and searchbility with tabs for deployment contracts

.github/workflows/certora-prover.yml
change certora prover to run on main
change certora prover to run on main
**Result:**
change certora prover to run on main
=> ci: change certora prover to run on main

.github/workflows/foundry-post-merge.yml, .github/workflows/foundry.yml
not every commit or code change need a 2h intense test, only solidity and workflow config changes need
add path filter for intense test
**Result:**
only solidity and workflow config changes will trigger intense test
=> ci: add path filter for intense test

.github/workflows/delete-unauthrized-branches.yml
=> ci: add action to delete unauthorized branches that do not follow branching policy

CONTRIBUTING.md, README.md
callout consequences of not follow contribution guidelines
call things out explicitly
=> docs: callout consequences of not follow contribution guidelines

src/contracts/token/Eigen.sol, src/test/token/EigenWrapping.t.sol
add TokenWrapped and TokenUnwrapped events in Eigen for observability
add TokenWrapped and TokenUnwrapped events in Eigen
add corresponding tests
**Result:**
we can track wrapping/unwrapping actions between Eigen and BackingEigen
=> feat: add TokenWrapped and TokenUnwrapped events in Eigen for observability

MAINTENANCE.md
docs: enrich MAINTENANCE.md re: release branches
clarify release-dev branch, their meanings and names
=> docs: enrich MAINTENANCE.md re: release branches

script/releases/Env.sol, script/releases/v1.6.0-moocow-and-elip5/1-deployContracts.s.sol, script/releases/v1.6.0-moocow-and-elip5/2-queueUpgrade.s.sol, script/releases/v1.6.0-moocow-and-elip5/3-executeUpgrade.s.sol, script/releases/v1.6.0-moocow-and-elip5/upgrade.json
add deploy script and tests of elip5
add deploy script and tests of elip5
**Result:**
add deploy script and tests of elip5
=> feat: add deploy script of elip5

script/releases/v1.6.0-moocow-and-elip5/1-deployContracts.s.sol, src/contracts/token/Eigen.sol, src/test/harnesses/EigenHarness.sol
add semver to eigen 
add semver to eigen 
**Result:**
add semver to eigen
=> feat: add semver to eigen

script/releases/README.md
docs: add doc for steps to write deploy scripts
=> docs: add doc for steps to write deploy scripts

CHANGELOG/CHANGELOG-1.5.0.md, CHANGELOG/CHANGELOG-1.6.0.md, CHANGELOG/CHANGELOG-1.7.0.md, CHANGELOG/CHANGELOG-template.md, MAINTENANCE.md
improve our release management and legibility
- add CHANGLOG structure and template
- add prefilled CHANGELOG for upcoming 3 releases
=> docs: add templates for changelog and release notes

.github/workflows/automation.yml, .github/workflows/foundry-post-merge.yml, .github/workflows/foundry.yml, .github/workflows/validate-deployment-scripts.yml
add explicit permission to all core repo CIs, and address security concerns and alerts
add explicit permission to all core repo CIs
**Result:**
workflows are safe now
=> ci: add explicit permissions to workflows to  mitigate security concerns

src/test/integration/IntegrationDeployer.t.sol
Fix forktest setup for redistribution.
=> fix: forktest setup

src/contracts/core/AllocationManager.sol, src/contracts/core/AllocationManagerStorage.sol, src/contracts/core/SlashEscrowFactory.sol
Redistribution nits from @nadir-akhtar 
- Reduce diff
- Style updates
- Clearer comments
**Result:**
Cleaner code
=> chore: address redistribution nits

foundry.toml, src/contracts/multichain/BN254CertificateVerifier.sol, src/contracts/multichain/BN254CertificateVerifierStorage.sol, src/test/integration/tests/ALM_Multi.t.sol, src/test/unit/BN254CertificateVerifierUnit.t.sol
Minor updates for `BN254CertificateVerifier` 
- Update interface
- Use types for `OperatorTableUpdater`
- Remove ownable
**Result:**
Minor Updates
=> chore: update BN254CertificateVerifier

README.md
update eigenpod and eigen impls addresses in holesky and hoodi
update eigenpod and eigen impls addresses in holesky and hoodi
**Result:**
update eigenpod and eigen impls addresses in holesky and hoodi
=> chore: update eigenpod and eigen impls addresses in holesky and hoodi

src/contracts/core/ReleaseManager.sol, src/contracts/core/ReleaseManagerStorage.sol, src/contracts/interfaces/IReleaseManager.sol, src/test/unit/ReleaseManagerUnit.t.sol
=> feat: add `publishMetadataURI`

CHANGELOG/CHANGELOG-1.7.0.md, docs/multichain/source/CrossChainRegistry.md
Changelog for multichain
Generate changeling per guidelines
**Result:**
Release-ready
=> docs: changelog

docs/core/StrategyManager.md, src/contracts/core/AllocationManager.sol, src/test/utils/Logger.t.sol
We want to address a few nits.
- slash's -> operator set's.
**Result:**
Nits addressed.
=> docs(redistribution-changes): cleanup

CHANGELOG/CHANGELOG-1.5.0.md
Want up to date changelog.
- Updated changelog.
**Result:**
Up-to-date changelog.
=> docs: update CHANGELOG

docs/multichain/destination/CertificateVerifier.md, src/contracts/interfaces/IECDSACertificateVerifier.sol, src/contracts/multichain/BN254CertificateVerifier.sol, src/contracts/multichain/ECDSACertificateVerifier.sol, src/contracts/permissions/KeyRegistrar.sol
Fixes as a result of internal security review.
* Moved complex logic into separate private function
* Ordered functions according to correct category
* Updated documentation to latest state of codebase
**Result:**
* Cleaner code
* More accurate documentation
=> fix: multichain clarity updates

src/test/integration/MultichainIntegrationBase.t.sol, src/test/integration/tests/Multichain_Full_Flow.t.sol, src/test/integration/tests/Multichain_Generation_Reservation_Removal.t.sol, src/test/integration/tests/Multichain_Timing_Tests.t.sol
=> test: multichain integration tests

docs/multichain/README.md
Fix a typo in the `multichain` docs
=> fix: typo 

src/test/integration/MultichainIntegrationChecks.t.sol, src/test/integration/tests/Multichain_Full_Flow.t.sol, src/test/integration/tests/Multichain_Generation_Reservation_Removal.t.sol, src/test/integration/tests/Multichain_Timing_Tests.t.sol
=> test: more integration test scenarios and checks file

README.md
Add contract addresses for multichain
=> docs: multichain

src/contracts/core/ReleaseManager.sol, src/contracts/core/ReleaseManagerStorage.sol, src/contracts/interfaces/IReleaseManager.sol
After an internal security review, a few helpful fixes were determined for code clarity and reduced complexity.
* Reduced complexity for publishing release
* More appropriate function visibility
**Result:**
Cleaner, safer code
=> fix: Release Manager internal review fixes
