Layr-Labs/eigenlayer-contracts

src/contracts/interfaces/IServiceManager.sol
src/contracts/middleware/BLSRegistry.sol
src/contracts/middleware/RegistryBase.sol
src/contracts/middleware/example/ECDSARegistry.sol
src/contracts/middleware/example/HashThreshold.sol

Added a simple little middleware that allows validators to sign off on on a msg to confirm it. A dispute can be launched that hashes the message 1000 times and if the message doesnt start with a threshold amount of zeros, then all validators that signed are slashed.
I also added a ECDSA registry.
Planning to comment a bit soon, but mostly should be self explanatory for reviewers.
This will help middlewares get a better idea of how to integrate as we realized we didn't have a service manager implementation in the repo and the BLS registry contains a bit of logic that is unneccesary for peeps not using BLS.
TODO:
- Add tests for ECDSA registry
- ~~Add Natspec and more inline comments~~

Add middleware

---

src/test/utils/Operators.sol
src/test/utils/Owners.sol

Title. Silences the below warnings.
```console
warning[2018]: Warning: Function state mutability can be restricted to pure
--> src/test/utils/Operators.sol:16:5:
|
16 |     function operatorPrefix(uint256 index) public returns(string memory) {
|     ^ (Relevant source part starts here and spans across multiple lines).
warning[2018]: Warning: Function state mutability can be restricted to pure
--> src/test/utils/Owners.sol:16:5:
|
16 |     function ownerPrefix(uint256 index) public returns(string memory) {
|     ^ (Relevant source part starts here and spans across multiple lines).
```

Restrict state mutability to pure to silence warnings.

---

src/contracts/core/Slasher.sol
src/contracts/interfaces/IServiceManager.sol
src/contracts/interfaces/ISlasher.sol
src/contracts/middleware/RegistryBase.sol
src/contracts/middleware/example/HashThreshold.sol
src/test/DepositWithdraw.t.sol
src/test/Slasher.t.sol
src/test/mocks/MiddlewareRegistryMock.sol
src/test/mocks/MiddlewareVoteWeigherMock.sol
src/test/mocks/ServiceManagerMock.sol
src/test/mocks/SlasherMock.sol
src/test/unit/SlasherUnit.t.sol

We want to keep the updateBlock/latestServeUntil(block) logic consistent, so this switches the slasher to denominate entirely in blocks.

switch from latestTime to latestServeUntilBlock

---

src/contracts/libraries/BN254.sol
src/contracts/libraries/BeaconChainProofs.sol
src/contracts/libraries/Merkle.sol

as noted in https://github.com/Layr-Labs/eigenlayer-contracts/issues/8, looks like we missed a few license notes/identifiers, probably mostly due to typos of 'UNLICENCED' instead of 'UNLICENSED'

correct licensing

---

certora/harnesses/StrategyManagerHarness.sol
certora/specs/core/Slasher.spec
certora/specs/core/StrategyManager.spec
src/contracts/core/StrategyManager.sol

Inspired by SushiSwap router hack. Add a Prover rule that shows that we never transfer tokens out of an account other than the caller. (or conversely, if a user's token balance decreases as the result of a call to our contract(s), then that user must be the caller).
PR also comments out an old (failing) draft rule.

Add new prover rule

---

docs/AVS-Guide.md

Noticed a few broken links while reviewing this document. Also pulled links into vars for easier reuse and upgradability

fix broken links in avs guide

---

src/test/unit/StrategyBaseTVLLimitsUnit.sol
src/test/unit/StrategyBaseUnit.t.sol

make StrategyBaseTVLLimitsUnitTests also run the existing StrategyBaseUnitTests against the strategyWithTVLLimits
- have StrategyBaseTVLLimitsUnitTests inherit from StrategyBaseUnitTests
- modify setup so existing tests run against version with TVL limits
- add filtering for fuzzed inputs to existing tests
- fix initialization and add a check for this

Reuse Existing Unit Tests for strategyWithTVLLimits

---

foundry.toml

This PR remove the duplicate foundry remappings.
Fix #9

Chore: remove duplicate remappings

---

src/contracts/interfaces/IIndexRegistry.sol
src/contracts/middleware/IndexRegistry.sol
src/test/mocks/RegistryCoordinatorMock.sol
src/test/unit/DelayedWithdrawalRouterUnit.t.sol
src/test/unit/IndexRegistryUnit.t.sol

Adds a separate registry for managing operators position in a list of operatorsIds both globally and on a quorum-by-quorum basis

added indexregistry

---

src/contracts/interfaces/IBLSPubkeyRegistry.sol
src/contracts/middleware/BLSPubkeyRegistry.sol
src/contracts/middleware/BLSRegistryCoordinatorWithIndices.sol
src/test/unit/BLSPubkeyRegistryUnit.t.sol

Proposal and PR to remove tracking of the Global Apk. This is a bunch more uneeded gas for operators and we would basically never use it. The only place we would use it is iff we were checking signatures for 255 quorums and wanted to subtract 1 quorum apk from the global instead of adding the 255 quorum APKs.

remove global apk tracking

---

src/contracts/interfaces/IBLSPubkeyRegistry.sol
src/contracts/middleware/BLSPubkeyRegistry.sol
src/test/unit/BLSPubkeyRegistryUnit.t.sol

update storage to include a bytes24 instead of a bytes32 to save on storage. this doesn't effect security since ethereum has 20 byte addresses.

change apkupdate storage

---

src/contracts/libraries/BitmapUtils.sol

Function was using the `return` bytecode, which not only returns from the present function, but returns the entire transaction (pops the entire stack). Therefore, upstream functions would just not finish their execution, which would cause bugs.
My specific bug was when trying to register my operator with the `BLSRegistryCoordinatorWithIndices`.The [call to the bitmap function](https://github.com/Layr-Labs/eigenlayer-contracts/blob/378ae85785f970208bafc824180419b00b9dfe41/src/contracts/middleware/BLSRegistryCoordinatorWithIndices.sol#L291) would simply exit the current execution, causing the operator not to be able to register.
I haven't ran any tests though, so please do make sure this fix doesn't break other things if we do have tests.
Reference for return bytecode semantic:
- …

fix orderedBytesArrayToBitmap_Yul function

---

src/test/mocks/ERC20Mock.sol

moving _mint function to _transfer since it was currently only being applied in transferFrom and not transfer
Let me know if this was intended behavior and not a bug.

Fix erc20mock transfer not minting

---

docs/docgen/core/Slasher.md
docs/docgen/interfaces/ISlasher.md
src/contracts/core/Slasher.sol
src/contracts/interfaces/ISlasher.sol
src/test/DepositWithdraw.t.sol
src/test/mocks/SlasherMock.sol

This name looked like a typo (compare to getMiddlewareTimesIndexServeUntilBlock just below), so I fixed it to follow same name convention

getMiddlewareTimesIndexBlock -> getMiddlewareTimesIndexStalestUpdateBlock

---

src/contracts/libraries/BeaconChainProofs.sol
src/contracts/libraries/Endian.sol
src/contracts/libraries/Merkle.sol

contracts still have fixed pragma statements; I've conducted a manual review of known compiler bugs and do not believe that this should expose downstream users of these libraries to any _known_ compiler bugs

relax the pragmas for the libraries that we import from our interfaces

---

src/contracts/interfaces/IBLSPublicKeyCompendium.sol
src/contracts/middleware/BLSPublicKeyCompendium.sol
src/test/mocks/BLSPublicKeyCompendiumMock.sol
src/test/unit/BLSPublicKeyCompendiumUnit.t.sol

This is a more elegant, efficient scheme for checking signatures when people registry their BLS keys: https://github.com/Layr-Labs/eigenda/pull/86#discussion_r1259788515

Updated BLS Pubkey Registration

---

src/contracts/interfaces/IBLSRegistryCoordinatorWithIndices.sol
src/contracts/interfaces/IDelegationManager.sol
src/contracts/interfaces/ISignatureUtils.sol
src/contracts/middleware/BLSRegistryCoordinatorWithIndices.sol
src/test/unit/BLSRegistryCoordinatorWithIndicesUnit.t.sol
src/test/unit/DelegationUnit.t.sol
src/test/utils/MockAVSDeployer.sol

Added churner role and tests for it
Tests summary/updates:
- Added utility for churner to sign on OperatorChurnApprovals
- Added tests for 
- Expired signatures
- Invalid signatures
- Added churner signatures to existing happy path test cases
- Abstracted internal logic from operator kicking tests

Permissioned operator churn

---

script/DepositAndDelegate.s.sol
script/whitelist/Staker.sol
src/contracts/core/DelegationManager.sol
src/contracts/core/DelegationManagerStorage.sol
src/contracts/interfaces/IDelegationManager.sol
src/test/Delegation.t.sol
src/test/EigenLayerTestHelper.t.sol
src/test/EigenPod.t.sol
src/test/mocks/DelegationMock.sol
src/test/unit/DelegationUnit.t.sol
src/test/unit/StrategyManagerUnit.t.sol

See issue for some context: https://github.com/Layr-Labs/eigenlayer-contracts/issues/117 This commit also adds a simple test to verify that salt-reuse is properly disallowed, and modifies existing tests to work with the updated interface.

Switch from nonces to salts for DelegationApprovals

---

src/contracts/middleware/BLSRegistryCoordinatorWithIndices.sol
src/test/unit/BLSRegistryCoordinatorWithIndicesUnit.t.sol
src/test/utils/MockAVSDeployer.sol

this pr adds quorumNumbers to the struct that is signed by the churner to lock in the order of the operator kick params with the quorum numbers

add quorum numbers

---

.github/workflows/test.yml
go.mod
go.sum
src/test/ffi/BLSPubKeyCompendiumFFI.t.sol
src/test/ffi/BLSSignatureCheckerFFI.t.sol
src/test/ffi/g2pubkey.go
src/test/ffi/go/g2mul.go
src/test/ffi/util/G2Operations.sol
src/test/unit/BLSPublicKeyCompendiumUnit.t.sol

[Test: Use ffi to fuzz BLS Signature tests #67](https://github.com/Layr-Labs/eigenda-internal/issues/67)
Currently our tests use hardcoded G2 values as G2 operations are overly expensive within the EVM. Using [ffi](https://book.getfoundry.sh/cheatcodes/ffi) we can call out to Go code for these operations and allow for fuzzing in tests related to BLS signatures

Add ffi for fuzzing G2 operations

---

src/contracts/interfaces/IStrategyManager.sol
src/test/mocks/StrategyManagerMock.sol

this is a public mapping so it has a getter function, but the function was not previously in the interface.

add `numWithdrawalsQueued` function to IStrategyManager interface

---

src/contracts/middleware/StakeRegistry.sol
src/test/unit/StakeRegistryUnit.t.sol

- Implementing the unit tests outlined in `src/test/unit/StakeRegistry.tree`
- Currently able to call `registerOperator` multiple times without reverting
- Add more inline comments and one line summary for the file

StakeRegistry: Implementing Outlined Unit Tests

---

docs/EigenLayer-deposit-flow.md
script/M1_Deploy.s.sol
script/misc/GoerliUpgrade1.s.sol
script/testing/M2_Deploy_From_Scratch.s.sol
src/contracts/interfaces/IEigenPod.sol
src/contracts/interfaces/IEigenPodManager.sol
src/contracts/libraries/BeaconChainProofs.sol
src/contracts/pods/EigenPod.sol
src/contracts/pods/EigenPodManager.sol
src/test/DepositWithdraw.t.sol
src/test/EigenLayerDeployer.t.sol
src/test/EigenPod.t.sol
src/test/SigP/EigenPodManagerNEW.sol
src/test/mocks/BeaconChainOracleMock.sol
src/test/mocks/EigenPodManagerMock.sol

This PR is to add historical summary proofs to our withdrawal verification to prove older withdrawals.
It also addresses some comments in the "newpodchanges" PR.
- update validatorIndex in the validatorInfo struct
- I think that mostRecentBalanceUpdateSlot doesn't need to be set when you verify your withdrawal credentials.  0 here seems fine to me, but I will let the reviewers see if they agree.
- Switch from slot to timestamp in storage and events
- Syntax change in call to verifyProof functions to spedify individual inputs

Assorted EigenPod Fixes/Cleanup

---

src/contracts/interfaces/IServiceManager.sol
src/contracts/middleware/ServiceManagerBase.sol
src/test/mocks/ServiceManagerMock.sol

We add a ServiceManagerBase abstract class that implements all of the "trivial" functions that just proxy to the slasher, and only leave for implementation:
- latestServeUntilBlock
- freezeOperator
- taskNumber
This way, AVS teams can derive their service manager from this base implementation without having to write a lot of redundant proxy contract calls.
This ServiceManagerBase depends on our registry contracts (registryCoordinator and stakeRegistry) so any team that uses their own registry will still need to implement their service manager from scratch. We could have an even more barebone ServiceManagerBase contract, but not sure how useful it would be.
There's one more change included in this PR, which is that I removed the `latestServeUntil` parameter from all the recordStakeUpdate …

ServiceManagerBase implementation + minor change to IServiceManager interface

---

src/contracts/interfaces/IBLSRegistryCoordinatorWithIndices.sol
src/contracts/middleware/BLSRegistryCoordinatorWithIndices.sol

Removed comments mentioning that the `BLSRegistryCoordinatorWithIndices ` contract is the `StakeRegistry` itself via inheritance.
Updated for clarity.

Update inline commenting for RegistryCoordinator

---

src/contracts/interfaces/IStrategy.sol

Added the shares() view function to the strategy interface, only the userUnderlying() method exists currently.

add shares getter in IStrategy.sol

---

docs/AVS-Guide.md

Proposing protocol specs (docs) updates per [issue 114 in the monorepo](https://github.com/Layr-Labs/ui-monorepo-v2/issues/114#issuecomment-1706643067).

Updating protocol specs including AVS-Guide.md per Docs issue 114

---

README.md

IDK how this was missing, it's in the C4 contest repo. Installing dependencies is obviously important.

add `forge install` to installation instructions

---

src/contracts/interfaces/IEigenPod.sol
src/contracts/libraries/BeaconChainProofs.sol
src/contracts/pods/EigenPod.sol
src/contracts/pods/EigenPodManager.sol
src/test/EigenPod.t.sol
src/test/mocks/EigenPodMock.sol
src/test/unit/EigenPodManagerUnit.t.sol

There are several small tasks we need to accomplish once the "newpodchanges" branch is merged into master:
- - external callable by anyone
- - external callable by pod owner
- - external callable by EPM
- - internal state changing
- - internal pure
The ticket covering this is https://github.com/Layr-Labs/eignlayr-contracts/issues/962

Further changes to newpodchanges

---

README.md
src/test/DepositWithdraw.t.sol
src/test/EigenLayerDeployer.t.sol

Description:
Tests fail if `RPC_MAINNET` and `CHAIN_ID` are not set prior to running tests. 
Updated setUp() functions to use try catch blocks if env vars are not defined.
- `CHAIN_ID` defaults to local 31337
- `RPC_MAINNET` defaults to LlamaNodes RPC url

Use default RPC and chain id during tests

---

src/contracts/pods/EigenPod.sol
src/test/EigenPod.t.sol

New pods deployed post M2 will not have an activate restaking() option.  They will have to prove their WC to withdraw

Combine activate restaking and deploy flows

---

script/whitelist/delegationFaucet/DelegationFaucet.sol
script/whitelist/delegationFaucet/DelegationFaucetStaker.sol
script/whitelist/delegationFaucet/DeployDelegationFaucet.sol
src/contracts/interfaces/IDelegationFaucet.sol
src/test/DelegationFaucet.t.sol

Description:
- For M2, we are creating a quorum with a dummy ERC20 token. Operators can call `DelegationFaucet.mintDepositAndDelegate` which uses a `DelegationFaucetStaker` contract (deploys per-operator if it doesn't already exist) that gets minted the dummy ERC20 token and delegates to the operator.
- Copied most of the logic over from `Whitelister.sol`
Todo:
- Events
- Further testing

DelegationFaucet for M2 Testnet

---

src/contracts/libraries/BitmapUtils.sol
src/contracts/middleware/BLSSignatureChecker.sol
src/contracts/middleware/StakeRegistry.sol
src/test/harnesses/BitmapUtilsWrapper.sol
src/test/unit/BitmapUtils.t.sol

adds a new function `BitmapUtils.numberIsInBitmap`, inspired by [this comment](https://github.com/Layr-Labs/eigenlayer-contracts/pull/35#discussion_r1336399266)
Unit test coverage and usage of the function are also added

Add function to bitmap utils library

---

src/contracts/core/DelegationManager.sol
src/contracts/core/StrategyManager.sol
src/contracts/interfaces/IStrategyManager.sol
src/test/mocks/StrategyManagerMock.sol

This PR updates the migrateQueuedWithdrawal function within the DM to migrate multiple queued withdrawals to easily batch multiple migrations. To handle updating multiple withdrawals without reverting, the `migrateQueuedWithdrawal` in the SM does not revert if the withdrawal has already been provided. We also remove all withdrawalRoot calculations from the DM. 
Migration tests will be added in subsequent PR.

Migrate multiple queued withdrawals

---

docs/core/DelegationManager.md
docs/core/EigenPodManager.md
docs/core/StrategyManager.md
src/contracts/core/DelegationManager.sol
src/contracts/core/StrategyManager.sol
src/contracts/pods/EigenPod.sol
src/contracts/pods/EigenPodManager.sol

Reasoning - these are just simple method calls. We can always add them back in a future upgrade, even without a migration.
I'm removing them now because people (auditors, bounty hunters, ...) find them confusing and because the code has changed so much that it's no longer clear that the slasher will work the way it was intended to when these modifiers were added.

Removed references to the slasher (left state variables alone)

---

src/test/DepositWithdraw.t.sol
src/test/EigenPod.t.sol
src/test/unit/DelegationUnit.t.sol
src/test/unit/StrategyManagerUnit.t.sol

Removes tests that are now failing because we got rid of "onlyNotFrozen" et al.
Also fixes broken EigenPod test. The test was broken because it was using the wrong value to calculate restaked balance after verifying withdrawal credentials.
I fixed it by just removing the line entirely because, as it turns out, the helper function used to deploy the pod and prove credentials also has a test for the exact same thing, except it uses the correct value.

Remove tests that were failing due to deleted slasher checks

---

certora/harnesses/StrategyManagerHarness.sol
certora/specs/core/StrategyManager.spec

Remove the `totalSharesGeqSumOfShares` invariant, since the way we are enforcing this is now split between the StrategyManager + DelegationManager (rather than being solely enforced by the StrategyManager). Add  a new `newSharesIncreaseTotalShares` rule in its place, which verifies the modified behavior around share changes, and in particular verifies that the StrategyManager still exhibits the same behavior as before, when considered in isolation of the DelegationManager (i.e. ignoring the new `removeShares` + `addShares` functions)

deprecate broken rule and add a new one

---

README.md
docs/experimental/AVS-Guide.md

Slasher contract is under heavy changes and redesign, so we should add an impossible-to-miss notice on our README.
This shouldn't however prevent AVS teams from starting to write their service managers and integrating with eigenlayer contracts. I have thus moved the AVS-Guide to `docs/experimental` instead of `docs/outdated`, and added a warning notice in there as well.

Added slasher deprecation notice to README

---

src/test/mocks/DelegationManagerMock.sol
src/test/unit/StrategyManagerUnit.t.sol

Description:
Additional testing coverage as [mentioned here](https://github.com/Layr-Labs/eigenlayer-contracts/pull/224#issuecomment-1759628467)
Updated the testing excel doc with tests for `addShares()`, `removeShares()`, and `withdrawSharesAsTokens()`
and removed the outdated commented out tests.

Additional StrategyManager test coverage

---

src/contracts/interfaces/IIndexRegistry.sol
src/test/unit/IndexRegistryUnit.t.sol

- Adds unit/fuzz tests for registration, reregistration, and getters
- Remove stale `GlobalIndexUpdate` event
In terms of readability, we overload the `OperatorIndexUpdate` struct such that the index represents different values in different contexts. Might be a good idea to separate this struct out into two for operator index updates and quorum updates.

IndexRegistry Tests

---

src/contracts/interfaces/IEigenPod.sol
src/contracts/pods/EigenPod.sol
src/test/EigenPod.t.sol
src/test/mocks/EigenPodMock.sol
src/test/unit/EigenPodUnit.t.sol
src/test/utils/EigenPodHarness.sol

This PR refactors the validator balance updater to process multiple balance updates.  We allow this for verifying withdrawal credentials and withdrawals, it makes sense to do it here as well

Validator Balance update Refactor

---

script/testing/M2_Deploy_From_Scratch.s.sol

Removing blspubkey compendium from deploy script since it was moved to eigenlayer-middleware repo with its own deployment script.

removed bls pubkeycompendium deployment from m2 deployment script

---

src/contracts/core/StrategyManagerStorage.sol
src/contracts/pods/EigenPodManagerStorage.sol

- Gap on StrategyManager decreased from size 41 to 40. Any contracts inheriting from SM will begin storage at the 201st slot
- 2nd to last gap on EigenPodManager increased from 40 to 43. The `status` variable now correctly begins at slot 201
This PR addresses the gap warnings from the storage layout script in #263

Update Gaps for EigenPodManager and StrategyManager

---

docs/core/DelegationManager.md
src/contracts/core/DelegationManager.sol
src/test/unit/DelegationUnit.t.sol

Make it so that withdrawals for 0 strats cannot occur
Special case:
- return bytes32(0) if undelegating with no delegatable shares

require cannot q withdrawal for 0 strategies and update docs

---

src/test/EigenPod.t.sol

a forbidden implicit type conversion slipped in, which was causing build errors. this minimal commit fixes the issue.

chore: fix compilation error

---

src/contracts/libraries/BeaconChainProofs.sol
src/contracts/pods/EigenPod.sol

Reordered some of the constant indexes to be in-order in `BeaconChainProofs.sol`
for better readability while comparing with the consensus specs (example here https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/beacon-chain.md#validator)
Also added some additional comments regarding the VERIFY_BALANCE_UPDATE_WINDOW_SECONDS checks

EigenPod: Small Cleanup and Commenting

---

src/test/EigenLayerTestHelper.t.sol
src/test/unit/DelegationUnit.t.sol
src/test/unit/EigenPodManagerUnit.t.sol

1) failure in a test that appears to be due to the fuzzed 'withdrawer' matching a Strategy's address -- see run here https://github.com/Layr-Labs/eigenlayer-contracts/actions/runs/6672856290/job/18137522930#step:5:46
2) failure in a test when the fuzzed 'staker' address matches a fixed operator address which we are using (the reverting behavior is intended in this case) -- see run here https://github.com/Layr-Labs/eigenlayer-contracts/actions/runs/6672856290/job/18137724519#step:5:116

chore: filter fuzzed inputs to fix 2 flaky test failures

---

.github/workflows/certora-prover.yml

Certora will be introducing v5 soon, which is expected to include breaking changes. Fixing the version at v4.13.1 should allow continuity until we make changes to upgrade.

chore: use a fixed prover version

---

src/contracts/libraries/BeaconChainProofs.sol
src/test/integration/IntegrationBase.t.sol
src/test/integration/IntegrationDeployer.t.sol
src/test/integration/README.md
src/test/integration/TimeMachine.t.sol
src/test/integration/User.t.sol
src/test/integration/mocks/BeaconChainMock.t.sol
src/test/integration/mocks/BeaconChainOracleMock.t.sol
src/test/integration/tests/Deposit_Delegate_Queue_Complete.t.sol

- fixes some error messages to display the correct function name
- added `BeaconChainMock`, a mock interface to the beacon chain which generates proofs for pod validators
- full support for native eth stakers using the `HOLDS_ETH` and `HOLDS_ALL` flags to generate users with one or more validators-worth of restaked eth. 
- eth granted to users is now a random multiple of 32 ether. users that are granted more than 1 validator-worth will create multiple validators in the same pod.

support native eth in integration tests

---

src/contracts/interfaces/IEigenPod.sol
src/contracts/pods/EigenPod.sol
src/test/EigenPod.t.sol
src/test/mocks/EigenPodMock.sol

Adding some read functions to EP contract that take in bls pubkey as input not pubkeyhash.  Duplicate of this PR but into m2-mainnet instead of master: https://github.com/Layr-Labs/eigenlayer-contracts/pull/338

Add Read Functions to M2 Mainnet

---

.gitignore
src/contracts/core/DelegationManager.sol
src/contracts/interfaces/IDelegationManager.sol
src/test/events/IDelegationManagerEvents.sol
src/test/mocks/DelegationManagerMock.sol
src/test/unit/DelegationUnit.t.sol

enable AVS to update their metadata uri by adding `function updateAVSMetadataURI` and `event AVSMetadataURIUpdated`
borrowed many from Yash's draft, and further polished
i'm not sure what unit tests to add, as there seems not much to test. If there is any, can you advise?

feat: enable AVS update metadata uri

---

script/middleware/DeployOpenEigenLayer.s.sol
script/milestone/M2Deploy.s.sol
script/testing/M2_Deploy_From_Scratch.s.sol
script/testing/M2_deploy_from_scratch.mainnet.config.json
src/contracts/core/DelegationManager.sol
src/test/Delegation.t.sol
src/test/DepositWithdraw.t.sol
src/test/EigenLayerDeployer.t.sol
src/test/EigenPod.t.sol
src/test/integration/IntegrationDeployer.t.sol
src/test/unit/DelegationUnit.t.sol

Description:
Removes the ability to modify `delegation.withdrawDelayBlocks()` and only settable in `initialize` as the BLSSignatureChecker in middleware depends on this withdrawal window and modifying `withdrawDelayBlocks` could make previous invalid signatures valid. Since we don't have plans on modifying this value the plan is to just remove the setter entirely.
Changes:
- `Delegation.initialize` and `Delegation._initializeWithdrawalDelayBlocks`
- Fixed all scripts and compile errors
- added a regression test for initializing <= MAX_WITHDRAWAL_DELAY_BLOCKS

Feat: Remove set withdrawal delay

---

.github/workflows/certora-prover.yml
certora/scripts/core/verifyDelegationManager.sh
certora/scripts/core/verifyStrategyManager.sh
certora/scripts/libraries/verifyStructuredLinkedList.sh
certora/scripts/pods/verifyEigenPodManager.sh
certora/scripts/strategies/verifyStrategyBase.sh

- switch from fixed v4.13.1 to floating / latest version
- implement minimal changes that (hopefully) make existing specs work with v5
This is a minimal PR to migrate from v4.13.1 to v5 _without breaking our specs_.
We will need to do more work to actually take full advantage of the new features in v5.

chore: migrate to certora prover v5

---

src/contracts/core/DelegationManager.sol
src/contracts/core/DelegationManagerStorage.sol
src/contracts/interfaces/IDelegationManager.sol
src/test/events/IDelegationManagerEvents.sol
src/test/mocks/DelegationManagerMock.sol
src/test/unit/DelegationUnit.t.sol

support avs<>operator mapping with new APIs

feat: support avs<>operator mapping with new APIs

---

docs/core/DelegationManager.md
docs/core/EigenPodManager.md
src/contracts/pods/EigenPod.sol
src/contracts/pods/EigenPodManager.sol
src/contracts/pods/EigenPodPausingConstants.sol

Docs:
* Updates EPM docs with `verifyBalanceUpdates` and `createPod` method signature change
* Adds docs for #363 
Changes:
* EPM.createPod and EPM.stake now pause at the top level. Previously, stake could be called during a pause if the pod owner had a pod deployed already
* EP.recoverTokens and EP.withdrawNonBeaconChainETHBalanceWei now have a pause flag

fix: update docs and ensure important state changing methods are pausable

---

src/test/mocks/StrategyManagerMock.sol
src/test/tree/DelegationManagerUnit.tree
src/test/unit/DelegationUnit.t.sol

Added some missing unit tests for `queueWithdrawals` and `completeQueuedWithdrawal`
Changes:
- Removed `setWithdrawalDelayBlocks` from tree file as it is now removed and withdrawalDelayBlocks is only initialized on each upgrade
- Added helpers `_deployAndDepositIntoStrategies`, `_setUpQueueWithdrawals`, `_setUpCompleteQueuedWithdrawal`, `_fuzzWithdrawalAmounts` for easier setup of fuzzing and testing

Test: Add back missing withdrawal tests to DelegationUnit.t.sol

---

docs/README.md
docs/core/EigenPodManager.md
docs/core/proofs/BeaconChainProofs.md

I've submitted this pull request to address a few minor issues I noticed in the project documentation. My changes are primarily focused on improving clarity and correctness. Here's a brief overview of the updates:
1. **Commit 915144e**: Corrected grammatical errors in the documentation regarding Merkle trees. Specifically, changed 'lets' to 'let's' and 'who's' to 'whose' in an example sentence. 
2. **Commit 44f5899**: Fixed a missing preposition in the EigenPodManager documentation. The phrase 'according the their' has been updated to 'according to their'. 
3. **Commit 91faca8e**: Resolved a typo in the EigenLayer middleware documentation link description. The word 'now' was changed to 'more'.
Thank you for considering these changes. I appreciate the opportunity to contribute to the …

Documentation Fixes: Grammar, Typos, and Prepositions

---

docs/core/DelegationManager.md
src/contracts/core/DelegationManager.sol
src/test/integration/IntegrationChecks.t.sol
src/test/integration/User.t.sol
src/test/integration/tests/Deposit_Delegate_Queue_Complete.t.sol
src/test/integration/tests/Deposit_Delegate_Redelegate_Complete.t.sol
src/test/integration/tests/Deposit_Delegate_Undelegate_Complete.t.sol
src/test/unit/DelegationUnit.t.sol

integration tests in particular are now slightly more flexible
NOTE: this fix doesn't actually work.
Something weird is going on, where the expected queued withdrawals calculated in `_getExpectedWithdrawalStructsForStaker` don't match the actually queued withdrawals.
It seems like things go one of two directions: withdrawals are missing for beacon chain ETH, or all withdrawals have the last strategy in the staker's array as their strategy, rather than the i-th strategy.
I can't figure out quite what the root cause is here. Tried adding some logging to the `_getExpectedWithdrawalStructsForStaker` function, which is how I got this deep.

chore: fix tests to work with modified behavior

---

src/contracts/core/AVSDirectory.sol
src/contracts/core/AVSDirectoryStorage.sol
src/contracts/core/DelegationManager.sol
src/contracts/core/DelegationManagerStorage.sol
src/contracts/interfaces/IAVSDirectory.sol
src/contracts/interfaces/IDelegationManager.sol
src/test/unit/AVSDirectoryUnit.t.sol
src/test/unit/DelegationUnit.t.sol

Due to contract bytecode size of the DelegationManager exceeding the 24KB limit, this is where I created a draft PR to decouple the operatorToAVS registration mapping in the DM and separate it into the AVSDirectory contract. I also removed the "DelegationManager.<error message>" portion out of the require strings to save bytes as well.
Initially marked as a draft to get more thoughts on this and tests need to be fixed.

refactor: decouple AVS<>Operator mapping from DelegationManager

---

src/test/events/IAVSDirectoryEvents.sol
src/test/mocks/ERC20Mock.sol
src/test/unit/AVSDirectoryUnit.t.sol
src/test/unit/DelegationUnit.t.sol
src/test/unit/EigenPodManagerUnit.t.sol
src/test/unit/StrategyManagerUnit.t.sol

Added back and fixed AVSDirectory unit tests, added unit test for pausing register/deregister functions as well
Fixed some tests failing on `--fuzz-runs 4096`

fix: operator<>AVS mapping tests

---

src/contracts/core/DelegationManager.sol
src/contracts/core/StrategyManager.sol
src/contracts/interfaces/IEigenPodManager.sol
src/contracts/interfaces/IStrategyManager.sol
src/contracts/pods/EigenPodManager.sol
src/test/events/IEigenPodManagerEvents.sol
src/test/mocks/DelegationManagerMock.sol
src/test/mocks/StrategyManagerMock.sol
src/test/unit/EigenPodManagerUnit.t.sol
src/test/unit/StrategyManagerUnit.t.sol

We need to handle the following indexing cases for LST & Native ETH
- podSharesUpdate on balance updates/proving WC
- podSharesUpdate on withdrawing as tokens
- podSharesUpdate on withdrawing as shares
- Deposit event when withdrawing as shares
This is needed for monitoring + will be useful for external parties to properly index shares
Companion doc: https://docs.google.com/document/d/1vjT_i9V1bAclJSS62YpCLAo3KDP2IsHVWCYjdMcfV5w/edit#heading=h.958kgw1yie6h

Feat: add event for beacon chain balance update

---

script/testing/M2_Deploy_From_Scratch.s.sol
src/test/integration/IntegrationBase.t.sol
src/test/integration/User.t.sol
src/test/integration/tests/Deposit_Delegate_Redelegate_Complete.t.sol
src/test/mocks/DelegationManagerMock.sol
src/test/mocks/ERC20Mock.sol
src/test/mocks/EigenPodManagerMock.sol
src/test/unit/DelegationUnit.t.sol
src/test/unit/EigenPod-PodManagerUnit.t.sol
src/test/unit/EigenPodUnit.t.sol

warnings were for unused or shadowed variables, or functions that could have stricter mutability

chore: fix numerous compiler warnings from script + test files

---

src/contracts/core/DelegationManager.sol
src/contracts/interfaces/IDelegationManager.sol
src/test/mocks/DelegationManagerMock.sol

Used to reduce gas costs for `_weightOfOperator` calls for avs-syncs. Below is the middleware PR that uses this addition.
https://github.com/Layr-Labs/eigenlayer-middleware/pull/170

feat: Operator shares view for avs-sync

---

src/contracts/core/StrategyManager.sol
src/contracts/core/StrategyManagerStorage.sol
src/test/integration/User.t.sol
src/test/unit/StrategyManagerUnit.t.sol

This provides additional signature replay protection for the `StrategyManager.depositIntoStrategyWithSignature` method
Specifically, it addresses the issue outlined in
https://mirror.xyz/curiousapple.eth/pFqAdW2LiJ-6S4sg_u1z08k4vK6BCJ33LcyXpnNb8yU where some ERC1271 wallets might be vulnerable to "replays" of signatures
While the theoretical "damage" would be ~zero
(allowing someone to deposit and credit the deposit to a user), adding this field to the typehash seems to be best practice, at least.

fix: add staker address to DEPOSIT typehash

---

.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/task.md

Hello,
I've found several broken links in ISSUE templates, this PR fixes them. 
Another issue to fix is to update part of the issue where project should be assigned (the link is also not working). To my knowledge, no LayerZero projects are publicly accessible.

fix: update ISSUE templates links

---

src/test/mocks/StrategyManagerMock.sol
src/test/unit/DelegationUnit.t.sol
src/test/unit/StrategyManagerUnit.t.sol

Test additions:
- reverting tests for `thirdPartyTransfersForbidden` in StrategyManagerUnit.t.sol and DelegationUnit.t.sol
- Setting `strategyWithdrawalDelayBlocks` in `_deployAndDepositIntoStrategies` helper. So now rolling to the earliest valid block to complete withdrawals is `block.number + delegationManager.getWithdrawalDelay(withdrawal.strategies)`
- Added back revert tests for "withdrawalDelayBlocks not passed" for both SM strategies and beaconStrat
- fixed some tests failing on high # of fuzz runs

test: unit tests for strategy config additions

---

src/contracts/libraries/Merkle.sol

this should be MIT licensed; looks like this was missed

fix: use correct license

---

src/contracts/core/DelegationManagerStorage.sol

`delegationApprover` was missing from the `DELEGATION_APPROVAL_TYPEHASH` definition

fix: correct eip712 typehash

---

docs/core/DelegationManager.md
src/contracts/core/DelegationManager.sol
src/test/Withdrawals.t.sol
src/test/unit/DelegationUnit.t.sol

- Prevents calls to `queueWithdrawal` if any `QueuedWithdrawalParams` contains a `withdrawer` that is not the caller
- `completeQueuedWithdrawal` is unaffected, so existing queued withdrawals should not change

feat: prevent queuing withdrawals to other addresses

---

docs/core/DelegationManager.md
src/contracts/core/DelegationManager.sol
src/test/unit/DelegationUnit.t.sol

`minWithdrawalDelayBLocks` only being set in initialize function. Adding back the admin setter here

fix: Add back setMinWithdrawalDelayBlocks

---

certora/specs/pods/EigenPodManager.spec
docs/core/EigenPodManager.md
script/deploy/mainnet/M2Deploy.s.sol
script/utils/validateStorage/validateUpgrade.sh
src/contracts/interfaces/IEigenPodManager.sol
src/contracts/pods/EigenPodManager.sol
src/contracts/pods/EigenPodManagerStorage.sol
src/test/DepositWithdraw.t.sol
src/test/EigenLayerDeployer.t.sol
src/test/EigenPod.t.sol
src/test/events/IEigenPodManagerEvents.sol
src/test/integration/IntegrationDeployer.t.sol
src/test/mocks/EigenPodManagerMock.sol
src/test/tree/EigenPodManagerUnit.tree
src/test/unit/EigenPod-PodManagerUnit.t.sol
src/test/unit/EigenPodManagerUnit.t.sol

We are no longer limiting maximum number of deployed eigenpods. EigenPodManager on mainnet has `maxPods` set to uint256 max https://etherscan.io/address/0x91E677b07F7AF907ec9a428aafA9fc14a0d3A338#readProxyContract
This is removing unused `maxPods` code

chore: remove maxPods

---

.env.example
certora/specs/pods/EigenPodManager.spec
docs/core/EigenPodManager.md
script/configs/holesky/M2_deploy_from_scratch.holesky.config.json
script/configs/holesky/M2_deploy_preprod.holesky.config.json
script/deploy/holesky/M2_Deploy_From_Scratch.s.sol
script/deploy/holesky/M2_Deploy_Preprod.s.sol
script/deploy/mainnet/M2Deploy.s.sol
script/utils/ExistingDeploymentParser.sol
script/utils/validateStorage/validateUpgrade.sh
src/contracts/interfaces/IEigenPodManager.sol
src/contracts/pods/EigenPod.sol
src/contracts/pods/EigenPodManager.sol
src/contracts/pods/EigenPodManagerStorage.sol
src/test/DepositWithdraw.t.sol
src/test/EigenLayerDeployer.t.sol
src/test/EigenPod.t.sol
src/test/events/IEigenPodManagerEvents.sol
src/test/harnesses/EigenPodHarness.sol
src/test/integration/IntegrationDeployer.t.sol
src/test/mocks/EigenPodManagerMock.sol
src/test/tree/EigenPodManagerUnit.tree
src/test/unit/EigenPod-PodManagerUnit.t.sol
src/test/unit/EigenPodManagerUnit.t.sol
src/test/unit/EigenPodUnit.t.sol

Holesky deployment scripts. Assumes deployment of permissioned multisigs and beaconChainOracle contract. Deployment config is in `script/configs/holesky/M2_deploy_from_scratch.holesky.config.json`. Some config constants for holesky found here https://github.com/eth-clients/holesky
Run script with command
```
forge script script/deploy/holesky/M2_Deploy_From_Scratch.s.sol --rpc-url $RPC_HOLESKY --private-key $PRIVATE_KEY --broadcast -vvvv
```
Locally with anvil node 
```
anvil --fork-url $RPC_HOLESKY
forge script script/deploy/holesky/M2_Deploy_From_Scratch.s.sol --rpc-url http://127.0.0.1:8545 --private-key $PRIVATE_KEY --broadcast -vvvv
```

feat: holesky deploy scripts

---

src/contracts/pods/EigenPod.sol
src/test/EigenPod.t.sol
src/test/harnesses/EigenPodHarness.sol
src/test/unit/EigenPodUnit.t.sol

Fixes an off-by-one error that could have caused withdrawals to get stuck in EigenPods.
This is because withdrawals are processed at the _end_ of the block in which they are posted (rather than at the top of the block), so the strict inequality of `require(timestamp > mostRecentWithdrawalTimestamp)` could cause withdrawals that are processed in the same block as `mostRecentWithdrawalTimestamp` is set to get stuck.
The fix is simply changing the inequality to be non-strict. PR contains a new regression test for the behavior.

fix: off-by-one error

---

src/test/integration/IntegrationBase.t.sol
src/test/integration/IntegrationDeployer.t.sol
src/test/integration/tests/Delegate_Deposit_Queue_Complete.t.sol
src/test/integration/tests/Deposit_Delegate_Queue_Complete.t.sol
src/test/integration/tests/Deposit_Delegate_Redelegate_Complete.t.sol
src/test/integration/tests/Deposit_Delegate_Undelegate_Complete.t.sol
src/test/integration/tests/Deposit_Delegate_UpdateBalance.t.sol
src/test/integration/tests/Deposit_Queue_Complete.t.sol
src/test/integration/tests/Deposit_Register_QueueWithdrawal_Complete.t.sol
src/test/integration/users/User.t.sol

* complete user migration en masse rather than passing in individual addresses
* improve logging around user creation and upgrading
* fix eigenpod withdrawal timestamps

test: clean up fork testing

---

.github/workflows/testinparallel.yml
foundry.toml
src/test/integration/IntegrationDeployer.t.sol
src/test/integration/README.md
src/test/integration/tests/Delegate_Deposit_Queue_Complete.t.sol
src/test/integration/tests/Deposit_Delegate_Queue_Complete.t.sol
src/test/integration/tests/Deposit_Delegate_Redelegate_Complete.t.sol
src/test/integration/tests/Deposit_Delegate_Undelegate_Complete.t.sol
src/test/integration/tests/Deposit_Delegate_UpdateBalance.t.sol
src/test/integration/tests/Deposit_Queue_Complete.t.sol
src/test/integration/tests/Deposit_Register_QueueWithdrawal_Complete.t.sol
src/test/unit/DelegationUnit.t.sol

* regular, non-forking integration tests are run with `forge t --mc Integration`
* mainnet fork tests are run with `env FOUNDRY_PROFILE=forktest forge t --mc Integration`
* mainnet fork tests use the `forktest` foundry profile, which i've defined to only have 20 fuzz runs to limit RPC spam
* i added some notes to the integration test README that describe future directions for reducing RPC spam so we can bump the mainnet fork test intensity up, but for now this works

chore: fork test via environment and custom foundry profile

---

.github/workflows/run-deploy-scripts.yml
script/configs/devnet/M2_deploy_from_scratch.anvil.config.json
script/deploy/devnet/M2_Deploy_From_Scratch.s.sol

This PR:
1. fixes the deploy from scratch script for anvil
2. moves the script into a /devnet subfolder (not sure why it wasn't like the others in goerli, holesky, miannet)
3. adds a github action to run this deploy script to make sure its always kept up-to-date
For 3.... should we be running this inside the `run parallel` github action to save on checkout/forge build costs?

fix: m2_deploy_from_scratch script for devnet

---

script/deploy/mainnet/M2Deploy.s.sol
src/contracts/interfaces/IEigenPod.sol
src/contracts/pods/EigenPod.sol
src/contracts/pods/EigenPodStorage.sol
src/test/EigenPod.t.sol
src/test/unit/EigenPodUnit.t.sol

* modify activateRestaking flow to use checkpointing
* remove withdrawNonBeaconChainETHBalanceWei in favor of checkpointing

feat: remove all use of the delayed withdrawal router

---

docs/core/PaymentCoordinator.md
src/contracts/core/PaymentCoordinator.sol
src/contracts/core/PaymentCoordinatorStorage.sol
src/test/unit/PaymentCoordinatorUnit.t.sol

Add off-chain assumptions from payments calculation
- `SNAPSHOT_CADENCE`: Requirement for `CALCULATION_INTERVAL_SECONDS ` to be a multiple of this value
- `amount <= MAX_PAYMENT_AMOUNT`. This is 1e38-1, the max possible value in iceberg to do math without a loss of precision

feat: add payments off-chain assumptions

---

src/contracts/core/DelegationManager.sol
src/contracts/core/DelegationManagerStorage.sol
src/contracts/interfaces/IDelegationManager.sol

Alternative approach to that in https://github.com/Layr-Labs/eigenlayer-contracts/pull/549
This is a much simpler, "lightweight" change, but involves adding additional storage + notably writing to one more storage slot per newly queued withdrawal.
This PR was opened for illustrative purposes; I think we can fairly easily solve the issue here by simply packing the new storage into the existing `pendingWithdrawals` mapping.

feat: add storage to track the epoch in which withdrawals were queued

---

src/test/integration/IntegrationBase.t.sol
src/test/integration/IntegrationChecks.t.sol
src/test/integration/IntegrationDeployer.t.sol
src/test/integration/TimeMachine.t.sol
src/test/integration/mocks/BeaconChainMock.t.sol
src/test/integration/mocks/EIP_4788_Oracle_Mock.t.sol
src/test/integration/tests/Test.t.sol
src/test/integration/users/User.t.sol
src/test/integration/users/User_M1.t.sol
src/test/integration/utils/PrintUtils.t.sol

Right now, this PR is solely focused on getting integration tests running for checkpoint proofs. It's super messy and needs a lot of cleaning up / clarifying interfaces / ABIs.
Check out:
*  `integration/tests/Test.t.sol` - I'm writing new pepe-related tests here
* `integration/mocks/BeaconChainMock.t.sol` - I'm simulating beacon chain things here

test: modify integration test framework to support pepe

---

script/deploy/mainnet/M2Deploy.s.sol
script/deploy/mainnet/M2_Mainnet_Upgrade.s.sol
src/contracts/interfaces/IEigenPod.sol
src/contracts/pods/EigenPod.sol
src/contracts/pods/EigenPodStorage.sol
src/test/EigenPod.t.sol
src/test/harnesses/EigenPodHarness.sol
src/test/integration/IntegrationBase.t.sol
src/test/integration/users/User.t.sol
src/test/unit/EigenPod-PodManagerUnit.t.sol
src/test/unit/EigenPodUnit.t.sol

This PR:
*  removes `EigenPod.activateRestaking` in favor of having the pod owner call `EigenPod.startCheckpoint`
* deprecates `EigenPod.mostRecentWithdrawalTimestamp`
Rationale:
* Removes a method from the interface, simplifying frontend support for Pre-M2 pods
Notes:
This changes `verifyWithdrawalCredentials` to no longer use `mostRecentWithdrawalTimestamp` to determine whether a proof timestamp is valid. This is the riskiest change in this PR and needs some thinking to ensure this doesn't miss any edge cases.
Comparing with the M2 usage of `mostRecentWithdrawalTimestamp`:
1. `verifyAndProcessWithdrawals` makes some requirements on `mostRecentWithdrawalTimestamp`, but this method has been removed entirely in the checkpoint system.
2. `verifyWithdrawalCredentials` requires that …

feat: remove activateRestaking in favor of startCheckpoint

---

.github/workflows/coverage.yml
package-lock.json
package.json

**Summary**:
This is a simple PR that enables code coverage using `forge coverage`. The only non-trivial piece is that forge coverage includes tests, scripts and other non-functional code as part of its coverage, so there's logic to strip these files out. Once the coverage site is generated, it's uploaded to S3 using an artifact action.
**How to view**:
- The bot will automatically post the coverage on your PR. You can look through the associated Github Action if you want the HTML report.
**Changelog**:
- bump hardhat version
- introduce a `coverage` job for GHA
- coverage job automatically computes coverage percentages, filtering out unnecessary files.
- coverage job then uploads report to s3 for review. 
- bot then posts the status on the PR.

Chore: Turn on code coverage

---

src/contracts/core/AVSDirectory.sol
src/contracts/interfaces/IAVSDirectory.sol
src/test/events/IAVSDirectoryEvents.sol
src/test/unit/AVSDirectoryUnit.t.sol

This PR adds the migration feature for operator sets. 
In lieu of adding additional storage, we use the previous `OperatorAVSStatus` mapping to gate migrations. If the operator is registered, we allow migration. Once the migration has completed, we deregister the operator from M2, which prevents future migrations.

feat: operator set migration

---

src/contracts/core/AVSDirectory.sol
src/contracts/core/AVSDirectoryStorage.sol
src/contracts/interfaces/IAVSDirectory.sol
src/test/events/IAVSDirectoryEvents.sol
src/test/unit/AVSDirectoryUnit.t.sol

Bring back the OperatorAVSRegistration storage that was previously overwritten.
Segregates the registration/deregistration on M2 Legacy & Operator Sets for consistency in offchain code paths. As a result, we remove the numAVSRegistered struct. 
The storage may be able to be condensed still, but haven't put further thought into this.   
Pending: Bring Back OpSet struct in a separate PR

feat: operator set migration; completely separate legacy and opset reg

---

src/contracts/interfaces/IStrategyFactory.sol
src/contracts/interfaces/IStrategyManager.sol
src/contracts/strategies/StrategyFactory.sol
src/test/unit/StrategyFactoryUnit.t.sol

Add pass throughs for `removeStrategiesFromDepositWhitelist` and `setThirdPartyTransfersForbidden`

feat: add pass thoughts for all `strategyWhitelister` gated functions

---

src/contracts/interfaces/IStrategyFactory.sol
src/contracts/strategies/StrategyFactory.sol
src/contracts/strategies/StrategyFactoryStorage.sol
src/test/unit/StrategyFactoryUnit.t.sol

* Addresses comments in Telegram, as well as EGN6-03

feat: change name of tokenStrategy mapping to deployedStrategies

---

src/contracts/core/AVSDirectory.sol
src/contracts/core/AVSDirectoryStorage.sol
src/test/unit/AVSDirectoryUnit.t.sol

Adds tracking in storage for:
`operatorSetMemberCount`: The total members (operators) within a given operator set.
* Adds an additional `SLOAD` and `SSTORE` on registrations and deregistrations.
`operatorSetCount`: The total number of operator sets.
* Adds an additional `SLOAD` and `SSTORE` on operator set creation.
`avsOperatorSetCount`: The total number of operator sets for a given AVS.
* Adds an additional `SLOAD` and `SSTORE` on operator set creation.

feat: track total members and sets

---

src/contracts/core/AVSDirectory.sol
src/test/unit/AVSDirectoryUnit.t.sol

- Prevent race condition when AVSs migrate & an AVS also deregisters operator during multi-block operation.

fix: block m2 deregistrations for opset AVSs

---

script/deploy/devnet/operatorSets/PopulateSRC.sol
src/contracts/core/StakeRootCompendium.sol
src/contracts/interfaces/IStakeRootCompendium.sol

- operatorSets deposit funds for proof charges
- charges are per strategy per proof
- operatorSets must maintain a `MINIMUM_DEPOSIT_BALANCE`, otherwise they can be lose their deposit balance and be removed from the stakeTree
- addresses the race condition with removing strategies right before proofs are submitted by setting a proofInterval  which calculationTimestamps need to be a multiple of and charging users according to how many proof intervals have passed
- the main downside is that the price is not modifiable. in the terrible case that we have to change the price due to a drop in ETH (idk if we'd even want to do this), we'd basically pause verifyStakeRoot , updateBalanceInfo for every operatorSet, update the price, and then unpause verifyStakeRoot,

add charging implementation

---

src/contracts/core/AVSDirectory.sol
src/contracts/core/AVSDirectoryStorage.sol
src/contracts/interfaces/IAVSDirectory.sol
src/test/mocks/AVSDirectoryMock.sol

Updates to slashing-magnitudes
1. Using `_encodeOperator` to get the encoded bytes32 of the operatorSets to use as mapping keys in `_queuedDeallocationIndices` and `_magnitudeUpdate`. Provides a small lookup optimization and helps for readability. This is used for internal functions as this would cause more confusion for public function mappings like `isOperatorSet`
2. `_modifyAllocations` checks for ascending order of encoded operatorSets. This is to check for duplicate operatorSets being passed in for allocation.
3. ~Checks for proper ordering of future allocations by comparing `allocationEffectTimestamp` with the latest checkpoint timestamp. This could be a potential issue if an operator configures their allocation delay to be less than the default but they have a pending allocation in …

feat: encoded operatorSet mapping keys and duplicate check

---

src/contracts/core/DelegationManager.sol
src/contracts/interfaces/IEigenPodManager.sol
src/contracts/pods/EigenPodManager.sol
src/contracts/pods/EigenPodManagerStorage.sol
src/test/mocks/EigenPodManagerMock.sol
src/test/unit/EigenPodManagerUnit.t.sol

`podOwnerShares` is now updated to be `podOwnerScaledShares` where all shares are scaled according to the podOwner's delegated operator (if there exists any) and their totalMagnitude. Only upon `withdrawSharesAsTokens` are scaled shares descaled into real ETH amounts and withdrawn.

feat: eigenpodManager scaled shares

---

script/deploy/devnet/operatorSets/DeployStrategies.s.sol
script/deploy/holesky/Eigen_Strategy_Deploy.s.sol
script/deploy/holesky/M2_Deploy_From_Scratch.s.sol
script/utils/ExistingDeploymentParser.sol
src/contracts/core/AVSDirectory.sol
src/contracts/core/AVSDirectoryStorage.sol
src/contracts/core/AllocationManager.sol
src/contracts/core/DelegationManager.sol
src/contracts/core/DelegationManagerStorage.sol
src/contracts/core/RewardsCoordinator.sol
src/contracts/core/Slasher.sol
src/contracts/core/StrategyManager.sol
src/contracts/core/StrategyManagerStorage.sol
src/contracts/interfaces/IDelegationManager.sol
src/contracts/interfaces/IStrategyFactory.sol
src/contracts/interfaces/IStrategyManager.sol
src/contracts/libraries/SlashingConstants.sol
src/contracts/strategies/StrategyFactory.sol
src/test/events/IStrategyManagerEvents.sol
src/test/integration/IntegrationBase.t.sol
src/test/integration/IntegrationDeployer.t.sol
src/test/mocks/StrategyManagerMock.sol
src/test/unit/AVSDirectoryUnit.t.sol
src/test/unit/StrategyFactoryUnit.t.sol
src/test/unit/StrategyManagerUnit.t.sol

**Description**:
1. Includes support for legacy M2 withdrawals
The withdrawal struct has converted the uint32 `startBlock` field to `startTimestamp`. We simply check that this value is < `LEGACY_WITHDRAWALS_TIMESTAMP` (Jan 01 2025 17:00:00 GMT+0000) and process as an old legacy withdrawal if so. We just need to ensure this timestamped value is < whatever the current timestamp is when the upgrade takes place. It would take 600+ years for the current blocknumber on mainnet to reach this threshold. We should be good
3. Removing thirdPartyTransfersForbidden and deprecating the storage
**DM codesize after cleanup and optimizer-runs = 5**

feat: legacy withdrawals and cleanup for DelegationManager

---

src/contracts/core/DelegationManager.sol
src/contracts/core/StrategyManager.sol
src/contracts/interfaces/IStrategyManager.sol
src/test/mocks/StrategyManagerMock.sol

Receive as shares is essentially duplicated logic of deposits. This includes refactoring the addShares function in SM to call increaseDelegatedShares. Changes to EPM are still pending

refactor: receive as shares callback

---

.github/workflows/storage-report.yml
src/contracts/core/AVSDirectoryStorage.sol

Changes:
- Should now fail if there's a storage diff.

fix: fail on storage diff

---

src/contracts/core/StakeRootCompendium.sol
src/contracts/core/StakeRootCompendiumStorage.sol
src/contracts/interfaces/IStakeRootCompendium.sol

There was an accounting bug when updating params this is fixed.
I'm comfortable with the refactor in #766 , so i'm building off of that and just keeping this branch separate until there's another review. If we toss out the  #766 refactor I can migrate the fix.
- simplified the naming of `totalCharge` to `chargePerProof`
- removed an "optimization" in #766 of copying storage to memory to avoid multiple sloads, but with some profiling the gas cost of memory copying doesn't make up for fewer reads from the same slot. In general KISS. Let's not over optimize here. I understand avoiding reading from new slots and storage packing, but reading the same slot is cheap. better not to sweat the small stuff
- removed the assembly and replaced with readable code

feat: fixed accounting bug and refactoring

---

src/contracts/core/DelegationManager.sol
src/contracts/core/DelegationManagerStorage.sol
src/contracts/interfaces/IDelegationManager.sol
src/contracts/interfaces/IEigenPod.sol
src/contracts/interfaces/IEigenPodManager.sol
src/contracts/libraries/SlashingLib.sol
src/contracts/pods/EigenPod.sol
src/contracts/pods/EigenPodManager.sol
src/contracts/pods/EigenPodStorage.sol

This proposal
- this would get rid of negative shares (going forward)
- more intuitive slashing model between LSTs and EigenPods
by using a separate beaconChainScalingFactor that is decreased upon negative deltas
Since EigenPods are updated to record a _proportion delta_ in the EPM instead of the abosolute share delta upon deposits, an "edge" case exists where uncompleted checkpoints exist during the slashing upgrade and can no longer call back to the EPM.
I'm still looking into it but I believe our choices are the following:
1. Pause/Unpause
a. pause checkpoint creation
b. complete all existing checkpoints
c. execute the slashing upgrade
d. unpause checkpoint creation (we'd already have an unpause tx in the timelock controller)
2. Upgrade pods in UNIPRINT
a. upgrade EigenPod.sol in …

eigenpods slashing updates

---

src/contracts/core/AllocationManager.sol
src/contracts/core/AllocationManagerStorage.sol
src/contracts/interfaces/IAllocationManager.sol
src/test/events/IRewardsCoordinatorEvents.sol
src/test/mocks/DelegationManagerMock.sol
src/test/mocks/EigenPodManagerMock.sol
src/test/mocks/StrategyManagerMock.sol
src/test/unit/EigenPodManagerUnit.t.sol
src/test/unit/StrategyManagerUnit.t.sol

- Takes advantage of only 1 alloc/dealloc at at time to simplify storage

Feat: AllocationManager Storage Simplification 

---

docs/core/StrategyManager.md

Adding clarification to depositIntoStrategyWithSignature() per customer question in Slack.

Clarifying depositIntoStrategyWithSignature() purpose

---

src/contracts/core/AllocationManager.sol
src/contracts/core/DelegationManager.sol
src/contracts/core/DelegationManagerStorage.sol
src/contracts/core/StrategyManager.sol
src/contracts/core/StrategyManagerStorage.sol
src/contracts/interfaces/IDelegationManager.sol
src/contracts/interfaces/IEigenPodManager.sol
src/contracts/interfaces/IShareManager.sol
src/contracts/interfaces/IStrategyManager.sol
src/contracts/libraries/SlashingLib.sol
src/contracts/pods/EigenPodManager.sol
src/contracts/pods/EigenPodManagerStorage.sol
src/contracts/strategies/StrategyBase.sol

This PR updates the storage of the delegationManager to store the operator's magnitude as part of its shares. Thus, we essentially store $$b_n$$ in this [doc](https://www.notion.so/eigen-labs/Slashing-Accounting-70dde029a6bb40628bcd56d351bf7e54#4caca6e758ab47e9a5edf26a19679596)
In doing so, we only need two types of shares
1. DepositShares: shares that are deposited in strategyManager/EPM
2. Shares: A concept native to DM. For a staker, this is withdrawable shares as we need to take into account scaling factors. For an operator, this is the sum of its stakers withdrawable shares. This lives in storage for the operator.  
What I'm looking for feedback on:
- How do we feel about removing custom types and going for `depositShares` and `shares` everywhere
- Naming of depositShares/shares
- …

DM Cleanup

---

script/configs/holesky/eigenlayer_addresses_preprod.config.json
script/deploy/holesky/upgrade_preprod_rewardsCoordinator.s.sol

upgrade for foundation incentives reward

feat: preprod rewards coordinator upgrade 

---

src/contracts/interfaces/IStrategyManager.sol
src/test/mocks/DelegationManagerMock.sol
src/test/unit/AllocationManagerUnit.t.sol

Nearly finishes testing plan. This coverage is sufficient for public devnet

Slashing: Add additional happy path AM test cases

---

src/contracts/core/AVSDirectoryStorage.sol
src/contracts/core/AllocationManagerStorage.sol

#814 adds a new storage variable to `AVSDirectoryStorage` but unintentionally decrements the gap in `AllocationManagerStorage`. This sets the storage gaps to their intended values.

Fix misset storage gaps

---

.github/workflows/coverage.yml

Has the same name as the testing file, causing CI assertions for `run-tests` to also require coverage to pass

Fix: Update coverage workflow job name

---

src/contracts/core/AllocationManager.sol
src/contracts/core/AllocationManagerStorage.sol
src/contracts/interfaces/IAllocationManager.sol
src/test/unit/AllocationManagerUnit.t.sol

See https://github.com/Layr-Labs/eigenlayer-contracts/pull/826

Fix: Single Deallocation Queue

---

src/contracts/core/DelegationManager.sol
src/contracts/core/DelegationManagerStorage.sol
src/test/integration/IntegrationDeployer.t.sol
src/test/unit/DelegationUnit.t.sol

Implements @MinisculeTarantula's suggestion to make this a bit clearer

Feat: Update legacy withdrawal timestamp param to legacy withdrawal check

---

.github/workflows/coverage.yml
docs/README.md
docs/release/slashing/AllocationManager.md
src/contracts/core/AllocationManager.sol
src/contracts/core/AllocationManagerStorage.sol
src/contracts/core/DelegationManager.sol
src/contracts/core/StrategyManager.sol
src/contracts/interfaces/IAVSDirectory.sol
src/contracts/interfaces/IAllocationManager.sol
src/contracts/interfaces/IDelegationManager.sol
src/contracts/libraries/SlashingLib.sol
src/test/DepositWithdraw.t.sol
src/test/DevnetLifecycle.t.sol
src/test/EigenLayerTestHelper.t.sol
src/test/integration/IntegrationChecks.t.sol
src/test/integration/tests/Deposit_Delegate_Queue_Complete.t.sol
src/test/integration/tests/Deposit_Delegate_Redelegate_Complete.t.sol
src/test/integration/tests/Deposit_Delegate_Undelegate_Complete.t.sol
src/test/integration/users/User.t.sol
src/test/unit/AllocationManagerUnit.t.sol
src/test/unit/DelegationUnit.t.sol

PR Fixes:
- https://github.com/Layr-Labs/eigenlayer-contracts/pull/679#discussion_r1769243035
- https://github.com/Layr-Labs/eigenlayer-contracts/pull/679#discussion_r1769256480 added legacy minWithdrawalDelayBlocks interfaces
- https://github.com/Layr-Labs/eigenlayer-contracts/pull/679#discussion_r1769370145 fixed interface to "numToClear" and added to natspec description
- https://github.com/Layr-Labs/eigenlayer-contracts/pull/679#discussion_r1769374303 addressed, see `modifyAllocations`
- https://github.com/Layr-Labs/eigenlayer-contracts/pull/679#discussion_r1769375520 added helpers using `Rounding.Up` in the OZ Math lib
- https://github.com/Layr-Labs/eigenlayer-contracts/pull/679#discussion_r1772293939 Allow for allocationDelays of 0 now …

slashing: cleanup

---

src/contracts/core/DelegationManager.sol
src/contracts/interfaces/IDelegationManager.sol
src/test/unit/DelegationUnit.t.sol

This handles edge cases of 100% slashed scenarios where an operator is fully slashed for a strategy(maxMagnitude = 0)
and also when a native restaker has had enough accrued delta decreases in their beacon chain shares to the point where their beaconChainScalingFactor is 0. Either of these situations will result in a divide by 0 and has more transparent error revert checks when this occurs. 
Changes:
- Undelegation from a fully slashed operator is also fixed now as the queue withdrawal is ignored and deposit shares are fully decreased.
- Delegated deposits (`increaseDelegatedShares`) to an operator for a strategy that is fully slashed will revert
- Queue withdrawals for a strategy that is fully slashed will revert
Note: Complete queued withdrawals are unchanged but perhaps should revert if …

slashing: fully slashed strategies

---

script/deploy/devnet/deploy_from_scratch.s.sol
src/contracts/core/DelegationManager.sol
src/contracts/core/DelegationManagerStorage.sol
src/contracts/interfaces/IDelegationManager.sol
src/test/DepositWithdraw.t.sol
src/test/DevnetLifecycle.t.sol
src/test/EigenLayerTestHelper.t.sol
src/test/integration/IntegrationDeployer.t.sol
src/test/integration/users/User.t.sol
src/test/unit/DelegationUnit.t.sol

Decided on keeping `struct Withdrawal` as using blocknumbers as opposed to converting to timestamps.
<s> However because the delay is going to change in the upcoming release to align with DEALLOCATION_DELAY in the AllocationManager, the withdrawal startBlock will need to be checked against the blocknumber of the Slashing upgrade. See `getCompletableTimestamp()` for details.
</s>
All legacy withdrawals queued prior to the upgrade will actually have their withdrawal delay extended by however long the new withdrawal delay period (17.5 day delay so extended by 10.5 days). Thus removing any branching logic for handling withdrawals and their timestamps. 
Additionally, `minWithdrawalDelayBlocks` will still be deprecated as having this lie in storage with a setter function is not practical. Any …

slashing: revert timestamps delegation

---

src/contracts/core/DelegationManager.sol
src/contracts/interfaces/IDelegationManager.sol
src/test/unit/DelegationUnit.t.sol

Changes the `SlashingWithdrawalQueued` event to emit the shares attempted for withdrawal, rather than deposit shares

fix: change to sharesToWithdraw

---

script/releases/release-template/2-multisig.s.sol
script/releases/v0.1-eigenpod-example/1-eoa.s.sol

This change introduces the requirement for users to explicitly title their contract when performing deployments. This name will be used by Zeus for tracking.

refactor: require "name" to be populated for deployments

---

script/tasks/complete_withdrawal_from_strategy.s.sol
src/contracts/core/DelegationManager.sol
src/contracts/core/DelegationManagerStorage.sol
src/contracts/core/StrategyManager.sol
src/contracts/interfaces/IDelegationManager.sol
src/contracts/interfaces/IEigenPod.sol
src/contracts/interfaces/IEigenPodManager.sol
src/contracts/libraries/SlashingLib.sol
src/contracts/pods/EigenPod.sol
src/contracts/pods/EigenPodManager.sol
src/contracts/pods/EigenPodManagerStorage.sol
src/contracts/pods/EigenPodStorage.sol
src/test/integration/IntegrationBase.t.sol
src/test/integration/tests/eigenpod/VerifyWC_StartCP_CompleteCP.t.sol
src/test/mocks/EigenPodManagerMock.sol
src/test/unit/DelegationUnit.t.sol
src/test/unit/EigenPodManagerUnit.t.sol

Changes:
* Removed `_beaconChainSlashingFactor` from `DelegationManager` and placed in `EigenPodManager`
* Altered equation used to decrease operator shares when beacon chain scaling factor is reduced (see `DM.decreaseDelegatedShares`)
* EigenPod checkpoints no longer deleted when complete. Checkpoint timestamps are reset to 0, but the struct itself is no longer deleted. This saves gas when creating a new checkpoint, because the state slot is not zeroed out.
* Removed slashing math calculation from EigenPod in favor of implementing this in `EPM._reduceSlashingFactor`. This removes a branch from EigenPods.
* `EPM.recordBeaconChainETHBalanceUpdate` branches cleaned up:
* Fixed bug where no update would occur when `podOwnerDepositShares == 0`
* Explicitly follow `_addShares` path when …

refactor: EigenPods and beacon chain slashing

---

src/test/integration/IntegrationChecks.t.sol
src/test/integration/tests/Deposit_Delegate_Queue_Complete.t.sol
src/test/unit/EigenPodManagerUnit.t.sol

Regression test for properly initializing `sharesToWithdraw`
- Comment out passing integration test
- Remove stale `fixMe` comment
- assert `withdrawSharesAsTokens` calls into EigenPod

test: `withdrawSharesAsTokens` regression

---

src/contracts/core/DelegationManager.sol
src/contracts/interfaces/IDelegationManager.sol

Remove checks on `delegateTo` for validating the `msg.sender` is not the operator or delegationApprover when there is an approver. not needed since this function is called by stakers

chore: remove unnecessary delegate checks

---

src/contracts/core/RewardsCoordinator.sol
src/test/unit/RewardsCoordinatorUnit.t.sol

Operator Directed Rewards needs to have the existing upper bound on total amount so that it works well with the offchain rewards calculation.

fix: operator-directed rewards total amount upper bound

---

src/contracts/core/StrategyManager.sol
src/contracts/core/StrategyManagerStorage.sol
src/test/unit/StrategyManagerUnit.t.sol

To prevent a DOS situation of slashing an operatorSet's strategies, any reverts on the underlyingToken's transfer function are wrapped in a try catch block. In such scenario, these slashed shares will simply just sit in the Strategy contract unable to be withdrawn.

fix: try catch on burning

---

src/contracts/core/DelegationManager.sol
src/contracts/interfaces/IDelegationManager.sol
src/test/unit/DelegationUnit.t.sol

* add `redelegate`, a combination of `undelegate` and `delegateTo`
* refactors out common parts of each  method into helpers (`_undelegate` and `_checkApproverSignature`)
* reorders internal methods to make more sense (`queue` is now above `complete`)

feat: add redelegate

---

script/releases/v0.5.1-rewardsv2/3-multisig.s.sol

Asserting the Upgrade event in Zeus script.

test: rewards v2 upgrade event assertion in zeus script

---

script/configs/local/deploy_from_scratch.anvil.config.json

add `.rewardsCoordinator.default_operator_split_bips`

fix: add missing params

---

script/deploy/devnet/deploy_from_scratch.s.sol
script/deploy/local/Deploy_From_Scratch.s.sol
script/deploy/local/deploy_from_scratch.slashing.s.sol
src/contracts/permissions/PermissionController.sol
src/test/integration/IntegrationDeployer.t.sol
src/test/utils/EigenLayerUnitTestSetup.sol

- Removes `permissionController.initialize()` (was previously unimplemented).
- Small syntax nit

refactor: `PermissionController` cleanup

---

script/releases/v0.5.1-rewardsv2/2-multisig.s.sol
script/releases/v0.5.1-rewardsv2/3-multisig.s.sol

- Zeus scripts now explicitly state the multisig that they intend to run from.
- zSetMultisigContext is no longer needed, as the script implies its runner.
- Zeus 0.4.0 can now communicate with this standard.
NOTE:
- Will be supported in `zeus 0.4.0` (https://github.com/Layr-Labs/zeus/pull/5)
- We'll re-pin the upgrade to this commit.
- I redid the rewards V2 deploy from today here: ([final commit](https://github.com/jbrower95/eigenlayer-contracts-metadata/commit/33161b5545e6781d68d1606d2182ff0ea18585e5))
- Tenderly of redeploy: https://dashboard.tenderly.co/layrlabs/eigenlayer/testnet/cfd65c84-9ab2-4d4c-a175-fb725956b5fa

feat: explicit multisig syntax on zeus scripts

---

src/contracts/core/RewardsCoordinator.sol
src/contracts/interfaces/IRewardsCoordinator.sol

This PR addresses some of the informational findings found during the internal security review. Specifically, this PR:
* Arranges functions to match our EigenLayer style guide
* Makes a note on `processClaims()` about an array of too large a size potentially causing a user to hit gas limits, and recommending a smaller array in that circumstance

refactor: address informational security review findings

---

script/releases/v0.5.2-rewardsv2/1-eoa.s.sol
script/releases/v0.5.2-rewardsv2/2-multisig.s.sol
script/releases/v0.5.2-rewardsv2/3-multisig.s.sol
script/releases/v0.5.2-rewardsv2/upgrade.json

This is a patch to `v0.5.1` that sets sets `REWARDS_COORDINATOR_CALCULATION_INTERVAL_SECONDS` = `1 day` on pre-prod.

fix: patch rewards v2

---

src/contracts/core/RewardsCoordinator.sol
src/contracts/interfaces/IRewardsCoordinator.sol
src/test/unit/RewardsCoordinatorUnit.t.sol

Updates the RewardsCoordiator to be UAM-compliant:
- Removes UAM from the original AVS rewards submission (keeping interface the same here, and we want users to eventually move to operatorSet-based AVSs)
- Adds UAM to: setting PI split, setting AVS split, submitting operator directed rewards

feat: update rc for UAM

---

.github/workflows/testinparallel.yml
script/utils/ExistingDeploymentParser.sol
src/test/integration/IntegrationBase.t.sol
src/test/integration/IntegrationChecks.t.sol
src/test/integration/IntegrationDeployer.t.sol
src/test/integration/deprecatedInterfaces/mainnet/IDelegationManager.sol
src/test/integration/deprecatedInterfaces/mainnet/IEigenPod.sol
src/test/integration/deprecatedInterfaces/mainnet/IEigenPodManager.sol
src/test/integration/deprecatedInterfaces/mainnet/IStrategyManager.sol
src/test/integration/tests/Delegate_Deposit_Queue_Complete.t.sol
src/test/integration/tests/Deposit_Delegate_Allocate.t.sol
src/test/integration/tests/Upgrade_Setup.t.sol
src/test/integration/tests/eigenpod/EigenPod_Slashing_Migration.t.sol
src/test/integration/users/User_M1.t.sol
src/test/integration/users/User_M2.t.sol

This PR updates the integration testing framework for slashing by:
- Adding a new `User_M2` for M2 operations
- Getting all fork tests to pass in the CI (and updating the associated workflow)
- Adjusting assertions to handle M2 and slashing interfaces
It handles the following upgrade scenarios:
1. EigenPod migration: `Integration_EigenPod_Slashing_Migration` 
2. Queueing prior to the upgrade and completing after the upgrade: `testFuzz_delegate_deposit_queue_completeAsShares` and `testFuzz_delegate_deposit_queue_completeAsTokens`
TODOs in a separate PR:

feat: upgrade compatibility for integration tests + basic upgrade tests

---

.github/workflows/coverage.yml

Currently, we comment the coverage report frequently on every PR, taking up a lot of space on every PR but not providing much value. This PR logs the coverage report rather than comment it so that those seeking out this information can access it, while generally keeping PRs clean of this information.

chore: log rather than comment final coverage output

---

src/contracts/core/DelegationManager.sol
src/contracts/interfaces/IDelegationManager.sol
src/contracts/interfaces/IEigenPodManager.sol
src/contracts/pods/EigenPodManager.sol
src/test/harnesses/DelegationManagerHarness.sol
src/test/mocks/EigenPodManagerMock.sol
src/test/mocks/StrategyManagerMock.sol
src/test/unit/DelegationUnit.t.sol
src/test/utils/ArrayLib.sol

Refactored the calculation done for negative delta decreases for EigenPods.
This was due to failing fuzzed tests for `decreaseDelegatedShares` where the amount to decrement from operatorShares was exceeding the actual shares in storage and was underflowing. This change is logically equivalent and has less introduced error from using the `wadSlashed` paramater. The beaconChainSlashingFactor is effectively the "source of truth" for how much is slashed and we use that to calculate the operatorShares decreased. This is similar to how we calculate operatorShares to burn using prevMaxMagnitude and newMaxMagnitude. 
One thing to note is how when we calculate the newBeaconChainSlashingFactor, we are doing a mulDiv which rounds down. Meaning that eigenPod shares are rounded down, this is …

test: delegationManager unit test refactor

---

src/contracts/core/RewardsCoordinator.sol
src/test/unit/RewardsCoordinatorUnit.t.sol

Adding a lock on the activation delay for operator splits to ensure that an operator's existing split has to activate before that operator can set the split again.

fix: operator split activation delay lock

---

script/deploy/devnet/deploy_from_scratch.s.sol
src/contracts/core/DelegationManager.sol
src/contracts/core/DelegationManagerStorage.sol
src/contracts/interfaces/IDelegationManager.sol
src/test/DevnetLifecycle.t.sol
src/test/integration/IntegrationBase.t.sol
src/test/unit/DelegationUnit.t.sol
src/test/unit/StrategyManagerUnit.t.sol

This is so we don't break the BLSSigChecker on preprod/testnet

feat: add back minWithdrawalDelayBlocks for introspection

---

script/releases/v1.0.0-slashing/cleanup/start.sh
script/releases/v1.0.0-slashing/upgrade.json

- Adds a harness script `start.sh` for invoking the go binary. (must be executable).
- Expresses the arguments of the script -- a beacon node, an RPC node, and a privateKey.
Will be running this upgrade on a tenderly fork, through the script phase, to test this rollout. (For the final phase, we'll just provide a beacon holesky ETH2 node against the tenderly fork).

fix(slashing): fix upgrade script phase 4

---

src/contracts/core/DelegationManager.sol
src/contracts/interfaces/IDelegationManager.sol
src/contracts/libraries/SlashingLib.sol
src/test/unit/DelegationUnit.t.sol

added a view func for converting deposit shares from withdrawable shares

feat: add share helpers

---

src/contracts/core/AllocationManager.sol
src/contracts/core/DelegationManager.sol
src/contracts/interfaces/IAllocationManager.sol
src/test/unit/AllocationManagerUnit.t.sol
src/test/unit/DelegationUnit.t.sol
src/test/utils/ArrayLib.sol
src/test/utils/Random.sol

- removes unused `ISignatureUtils` import for `IAllocationManager`.
- add missing `InputArrayLengthMismatch()` check to `slashOperator()`.
- fix `getQueuedWithdrawals` bug + test

refactor: small cleanup

---

src/contracts/core/AllocationManager.sol
src/contracts/core/AllocationManagerStorage.sol
src/contracts/interfaces/IAllocationManager.sol
src/test/unit/AllocationManagerUnit.t.sol

We do not need this parameter any more since on `slashOperator` we don't loop through the list of strats in an opSet

feat: remove max strategies list

---

script/releases/v1.0.1-slashing/1-eoa.s.sol
script/releases/v1.0.1-slashing/2-multisig.s.sol
script/releases/v1.0.1-slashing/3-execute.s.sol

This PR patches the preprod release with the following bug fixes:
- https://github.com/Layr-Labs/eigenlayer-contracts/pull/959 -> fix incorrect indexing
- https://github.com/Layr-Labs/eigenlayer-contracts/pull/966 -> remove `numToComplete` interface
- https://github.com/Layr-Labs/eigenlayer-contracts/pull/965 -> align boundaries
It also adds the following:
- https://github.com/Layr-Labs/eigenlayer-contracts/pull/964 -> view function for withdrawable to deposit shares
- https://github.com/Layr-Labs/eigenlayer-contracts/pull/968 -> remove max strategy list length

feat: slashing patch upgrade script

---

src/contracts/interfaces/IAVSDirectory.sol

Removes:
- AVSMigratedToOperatorSets
- OperatorMigratedToOperatorSets

chore: remove unused `AVSDirectory` events

---

src/contracts/core/RewardsCoordinator.sol
src/test/unit/RewardsCoordinatorUnit.t.sol

As part of the Rewards v2 SigmaPrime audit, we need to tackle issue `ELSC2-07: Operators Can Lock In Current Default Split By Front-Running Changes`
* Moved `split <= ONE_HUNDRED_IN_BIPS` logic into common internal function : `_setOperatorSplit`
* Updated `_setOperatorSplit` and `_getOperatorSplit` for edge case of time after first split initialization, but before activation. 
* Updated tests.
Rewards v2 audit fixes.

fix: rewards v2 audit fixes

---

src/contracts/core/AllocationManager.sol
src/test/integration/users/User.t.sol
src/test/unit/AllocationManagerUnit.t.sol

This matches the effect block behavior to be similar to that of the allocation delay. Allocation configs updates are activated on the `17.5th day + 1 block`

fix: update alloc config delay bound

---

src/test/integration/IntegrationBase.t.sol
src/test/integration/IntegrationDeployer.t.sol
src/test/integration/mocks/BeaconChainMock.t.sol

* remove holesky fork logic
* condense upgrade and deploy flow across local/mainnet setups
* clean up unused variables

test: remove unneeded logic from integration test setup

---

bin/storage-diff.sh

```bash
> bash bin/storage-diff.sh --help                                                                                                                                                                    
Usage: bash bin/storage-diff.sh --rpc-url https://eth.llamarpc.com --etherscan-key 1234567890123456789012345678901234567890 --input contracts.json [--quiet] [--help]
Detects storage layout incompatibilities that could cause issues during upgrades.
Required:
-r, --rpc-url <url>         RPC endpoint URL for the target network (default: https://eth.llamarpc.com).
-e, --etherscan-key <key>   API key for Etherscan to fetch contract data.
Options:
-i, --input <file>          JSON file containing contract details, see format below (default: contracts.json).
If not provided, reads from stdin. …
```

feat: storage-diff.sh

---

src/contracts/core/AllocationManager.sol
src/test/unit/AllocationManagerUnit.t.sol

Due to casting not causing a revert in `_addInt128`, its possible to cast and truncate a value that overflows. This introduces several problems but the one outlined in the added test shows you can manipulate encumberedMagnitude to be 0 and infinitely allocate instead of being capped by maxMagnitude. 
This simple fix will now safecast and cause a revert if overflow occurs when downcasting to a `uint64`. If needed, we can only add a check on the input param so that the new magnitude allocation is <= WAD

fix: overflow bug for pendingDiff input

---

src/contracts/core/AllocationManager.sol
src/test/harnesses/AllocationManagerHarness.sol
src/test/unit/AllocationManagerUnit.t.sol

As a result of an existing deallocation being slashed such that its pendingDiff becomes an amount 0, it is possible
to call modifyAllocations and create a new allocation/deallocation overwriting the old deallocation in storage.
This could result in the deallocationQueue no longer being in ascending order by the deallocation's respective effectBlocks.
This prevents this edge case altogether by simply changing the check to use the effectBlock instead `require(allocation.effectBlock == 0, ModificationAlreadyPending());`

fix: overwriting existing pending modifications

---

docs/core/RewardsCoordinator.md

This PR adds additional documentation to `RewardsCoordinator.md` to describe the changes introduces by Rewards v2.1 (#1011).
**Modifications**:
* Introduction of `_operatorSetSplitBips` to the "Important state variables" section
* **New definitions** of "operator set" and "operator set key" in the "Helpful definitions" section
* Addition of two new functions: 
* `createOperatorDirectedOperatorSetRewardsSubmission`
* `setOperatorSetSplit`
* Updates to other functions since docs were last written (e.g. addition of `checkCanCall` modifier)
* Various formatting consistency fixes

docs: Rewards v2.1

---

.github/workflows/foundry.yml
foundry.toml
src/test/integration/IntegrationChecks.t.sol
src/test/integration/tests/Deposit_Delegate_Allocate.t.sol
src/test/unit/libraries/SnapshotsUnit.t.sol
src/test/unit/mixins/SignatureUtilsUnit.t.sol

Ensuring stricter code quality by preventing compilation warnings from being ignored. This helps catch potential issues early and enforces cleaner code.  
Set `deny_warnings` to *true* in `foundry.toml`.  
**Result:**  
Any compilation warnings will now cause a hard failure, enforcing stricter code hygiene and reducing the risk of overlooking potential issues.

fix: enforce no compile warnings

---

.github/workflows/certora-prover.yml
.github/workflows/coverage.yml
.github/workflows/deploy-local.yml
.github/workflows/format.yml
.github/workflows/storage-report.yml
.github/workflows/testinparallel.yml
src/contracts/pods/EigenPodManager.sol
src/test/integration/IntegrationBase.t.sol
src/test/integration/tests/upgrade/EigenPod_Negative_Shares.t.sol
src/test/integration/users/User.t.sol
src/test/integration/users/User_M2.t.sol
src/test/unit/EigenPodManagerUnit.t.sol

Fixes the negative shares edge case where an operator is overrewarded shares if a staker, who previously had negative shares, completes a withdrawal as shares. Integration upgrade tests have been added to verify behavior.

fix: ep negative shares bug

---

.github/workflows/foundry.yml
bin/storage-diff.sh
src/contracts/core/AVSDirectoryStorage.sol

Storage layout checker was incorrectly treating `__gap` variable overrides as critical errors, despite this being their intended use in upgradeable contracts.
- Added special handling for `__gap` variables
- Split issues into critical errors (storage overrides, removals) and warnings (gap overrides, renames)
- Updated error messages and return values accordingly
**Result:**
Script now properly validates storage layout changes, only failing on actually dangerous modifications while allowing intended gap usage.

feat: ci storage check required

---

src/contracts/core/DelegationManager.sol
src/contracts/interfaces/IDelegationManager.sol
src/test/unit/DelegationUnit.t.sol

add OperatorSharesSlashed event to track shares slashed per operator

feat: add OperatorSharesSlashed event to track shares slashed per operator

---

.zeus

- We're sunsetting the previous repository for our new repo.
- We're squashing commit history here in-case anything unintentional was added to that repo during the development of Zeus, as a pre-caution for Open Source.

chore: update to open source zeus repo

---

src/contracts/core/DelegationManager.sol
src/contracts/interfaces/IDelegationManager.sol
src/test/unit/DelegationUnit.t.sol

Users want a cost effective way to query withdrawable shares.
- added `getSharesFromQueuedWithdrawal(bytes32 withdrawalRoot)`
- renamed `getQueuedWithdrawals` to `getSharesFromQueuedWithdrawals`.
**Result:**
Users can query withdrawable shares with `withdrawalRoot` alone.

feat: add `getSharesFromQueuedWithdrawal`

---

src/contracts/core/AllocationManager.sol
src/contracts/libraries/OperatorSetLib.sol

- `OperatorSetLib.decode(operatorSet.key())` -> `operatorSet`

fix: funny syntax

---

docs/core/AllocationManager.md
src/contracts/interfaces/IAllocationManager.sol

We weren't documenting that small slashing amounts (`wadToSlash`) can round down to zero, preventing tokens from being marked for burning. This can result in tokens being permanently locked in the contract instead of burned as intended.  (EGSL-13)
- Added documentation note clarifying that small slashing amounts may not result in actual token burns due to rounding.  
- Ensured transparency in the slashing mechanism to prevent confusion about unburned but locked tokens.  
**Result:**  
- Clearer documentation on rounding behavior in the slashing mechanism.  
- Awareness that very small slashing amounts may not contribute to `burnableShares[strategy]`, avoiding unexpected outcomes.

docs: small slash amounts

---

src/contracts/core/DelegationManager.sol
src/test/unit/DelegationUnit.t.sol

Fixes an issue where `beaconChainETHStrategy` queued withdrawals were excluded from slashable shares tracking, leading to undercounted burnable shares. This ensures correct accounting for future ETH burning post-Ethereum Pectra upgrade.  (EGSL-03)
- Removed exclusion of `beaconChainETHStrategy` in `_addQueuedSlashableShares()`.  
- Updated tests to ensure correct tracking and slashing behavior.  
**Result:**  
- Proper tracking of `beaconChainETHStrategy` shares in slashing calculations.  
- Accurate burnable share accounting, preparing for future ETH burning.

fix: beaconchain slashable shares in queue

---

.github/workflows/foundry.yml

per chat w/ @0xClandestine , given continuous fuzzing tests takes too long (currently ~2.5h ish), we wanna make it only run when a commit is merged to dev branch, instead of every PR change
it should make the CI passes as a whole a lot faster, and save us huge money spent on github actions
make continuous fuzzing only run when a commit is merged to dev branch, instead of every PR change
**Result:**

refactor: limit continuous fuzzing to dev branch

---

src/contracts/interfaces/IPermissionController.sol

Audit report flagged that function selector-based permissions may break on upgrades. This PR documents the limitation and its implications while improving NatSpec for clarity. (EGSL-15)  
- Documented function selector upgrade invalidations.  
- Improved NatSpec comments in `IPermissionController`.  
**Result:**  
Clearer documentation on function selector limitations and enhanced NatSpec for better code clarity.

docs: upgrades can invalidate permissions

---

script/tasks/register_operator_to_operatorSet.s.sol
src/contracts/core/AllocationManager.sol
src/contracts/interfaces/IAVSRegistrar.sol
src/contracts/interfaces/IAllocationManager.sol
src/test/integration/users/AVS.t.sol
src/test/mocks/MockAVSRegistrar.sol
src/test/unit/AllocationManagerUnit.t.sol

Currently there is no way for an AVS implementing these callback functions of the IAVSRegistrar.sol to verify that the operatorSetIds belong to their operatorSets. The register/deregister callback functions are updated to include the address field. 
This PR is combining https://github.com/Layr-Labs/eigenlayer-contracts/pull/1092 and https://github.com/Layr-Labs/eigenlayer-contracts/pull/1085
Additionally, the try/catch design for deregistering from operatorSets was impacting state between AVS and core contracts due to not having proper gas estimates when submitting transactions. Solutions exploring passing some suitable gas paramter were explored but eventually removing it entirely was deemed the best solution.
- Added `avs()` view function that is …

refactor: registrar interfaces

---

src/contracts/core/DelegationManager.sol
src/contracts/core/StrategyManager.sol
src/contracts/pods/EigenPodManager.sol

Concerns about reentrancy in the DelegationManager and interactions of completed withdrawals which can call untrusted ERC20 transfers
Added reentrant guards across external functions
**Result:**
Preventing cross-function reentrancy in the DelegationManager

fix: reentrant guards

---

docs/core/StrategyManager.md
src/contracts/core/StrategyManager.sol

Fixes an issue arbitrary external contracts could be called via `StrategyManager.burnShares`. (Certora L-04)
`StrategyManager.burnShares` does not do an external call if the burnable share amount is zero
**Result:**
Should no longer be possible to call untrusted code directly through `burnShares`

fix: dont call strategy if we have no burnable shares

---

.github/workflows/foundry.yml

use more powerful machine to run CI and speed it up
we've tested in following combo:
- arch: x86 vs arm64
- cpu: 8 vs 16 vs 32 cores 
turns out our CI has best perf on x86 16core. 
use X86 16core runner i configured to run all CI jobs
**Result:**
improvements results:
- integration: 10min -> 4min, 2.5X
- forktest: 16min -> 4min, 4X
- intense fuzz tests: 2.5h -> 56min, 2.5X
- test storage: 13 min -> 2min, 6.5X
- coverage: 22min -> 8min, 3X

perf: use x86 16core machine for CI

---

.github/workflows/foundry.yml

Foundry tests only need to run when specific codebase paths are modified, rather than for all changes.  
For example, tests are not required when only documentation or deployment scripts are updated.  
- Added a list of code paths that trigger Foundry tests when modified.  
**Result:**  
- Speeds up CI for non-core contract changes.  
- Reduces CI costs.

perf: run Foundry CI tests only for relevant code changes

---

.github/workflows/foundry.yml
foundry.toml

After multiple improvements to other parts of our CI, the coverage job has become the longest-running task, limiting the total CI runtime.  
This PR significantly reduces the coverage runtime from **16-18 minutes** (already down from **26 minutes** thanks to a previous improvement using an x64 16-core runner) to just **2 minutes**—an **8-9x speedup**.  
- Parallelized coverage report generation.  
- Cached Foundry and Cargo artifacts.  
- Optimized Forge arguments.
**Result:**  
The coverage runtime is reduced from **16-18 minutes** (previously **26 minutes**) to **2 minutes**, achieving an **8-9x improvement**.

perf: speed up test coverage job in CI

---

certora/specs/core/Slasher.spec
certora/specs/libraries/StructuredLinkedList.spec
docs/README.md
docs/core/AVSDirectory.md
docs/core/AllocationManager.md
docs/core/DelegationManager.md
docs/core/RewardsCoordinator.md
docs/core/accounting/SharesAccountingEdgeCases.md
package.json
script/deploy/devnet/deploy_from_scratch.s.sol
script/utils/ExistingDeploymentParser.sol
src/contracts/core/AVSDirectory.sol
src/contracts/core/DelegationManager.sol
src/contracts/core/DelegationManagerStorage.sol
src/contracts/core/RewardsCoordinatorStorage.sol
src/contracts/interfaces/IAVSDirectory.sol
src/contracts/interfaces/IDelegationManager.sol
src/contracts/interfaces/IPermissionController.sol
src/contracts/interfaces/IRewardsCoordinator.sol
src/contracts/libraries/BytesLib.sol
src/contracts/strategies/EigenStrategy.sol
src/contracts/strategies/StrategyBase.sol
src/test/integration/IntegrationDeployer.t.sol
src/test/integration/users/User.t.sol
src/test/integration/users/User_M2.t.sol
src/test/tree/AllocationManagerUnit.tree
src/test/tree/PermissionControllerUnit.tree
src/test/unit/AllocationManagerUnit.t.sol
src/test/unit/DelegationUnit.t.sol
src/test/unit/EigenPodManagerUnit.t.sol

Tired of seeing PRs for minor misspellings—let's fix them all at once.  
- Used [typos-cli](https://github.com/crate-ci/typos) to automatically correct all misspellings across the repository.  
**Result:**  
A typo-free codebase... at least for now. 😅

docs: fix all misspellings

---

.github/workflows/foundry.yml

after a few rounds of optimization, the whole CI suite is now bounded by `coverage` job which is then bounded by the `install lcov` step that takes 3.5min to install lcov via apt
this PR changes to install lcov via prebuilt binary, instead of via apt, which shortens the installation from 3.5min to 1s
this PR changes to install lcov via prebuilt binary, instead of via apt
**Result:**
shortens the installation from 3.5min to 1s

perf: install lcov via prebuilt binary, instead of via apt

---

.github/workflows/foundry.yml

after multiple round of optimization, the bottleneck in CI is forge build now, which takes 1.2-1.5min
this PR added caching for forge build, so that every CI run can restore latest cache, and only compile solidity files that hv been changed, which significantly lowers compile time from 1.2-1.5min t0 <1s
this PR added caching for forge build, so that every CI run can restore latest cache, and only compile solidity files that hv been changed
**Result:**
significantly lowers compile time from 1.2-1.5min to <1s
before adding cache:
after adding cache:

perf: add cache for forge build

---

.github/configs/typos-cli.toml
.github/workflows/checks.yml
Makefile
certora/specs/core/Slasher.spec
src/contracts/core/AllocationManager.sol
src/test/integration/IntegrationChecks.t.sol
src/test/unit/EigenPodManagerUnit.t.sol

We frequently receive PRs for minor typo fixes. Recently, we addressed most of the typos in the repository (see #1119). However, this only corrects typos up to this point and does not prevent new typos from being introduced in the future.  
- Added a CI workflow to check for typos using [typos-cli](https://github.com/crate-ci/typos).  
**Result:**  
Typos will now be automatically detected and linted.

feat: add typos-cli ci check

---

docs/core/AllocationManager.md
src/contracts/core/AllocationManager.sol
src/contracts/core/AllocationManagerStorage.sol
src/contracts/interfaces/IAllocationManager.sol
src/test/integration/IntegrationBase.t.sol
src/test/integration/tests/Deposit_Delegate_Allocate_Slash_Queue_Redeposit.t.sol
src/test/integration/users/AVS.t.sol
src/test/unit/AllocationManagerUnit.t.sol

require avs register metadata in allocation manager before they can create operatorset

feat: require avs register metadata in allocation manager

---

src/contracts/core/DelegationManager.sol
src/contracts/interfaces/IDelegationManager.sol
src/test/unit/DelegationUnit.t.sol

Current fn only returns scaled shares, which leads integrators to making two calls. This is expensive in terms of gas.
- `getSharesFromQueuedWithdrawal` has been renamed to `getQueuedWithdrawalFromRoot` and now also returns `Withdrawal` struct.
**Result:**
Integrators can fetch both in a single call.

refactor: `getSharesForQueuedWithdrawal`

---

src/test/integration/IntegrationBase.t.sol
src/test/integration/IntegrationChecks.t.sol
src/test/integration/tests/ALM_RegisterAndModify.t.sol
src/test/integration/tests/SlashingWithdrawals.t.sol
src/test/integration/users/AVS.t.sol

Improve slashing invariants in integration tests
Adds `check_Base_Slashing_State`, and implements several checks used within
**Result:**
Slashing invariants check all manner of state changes in the ALM and delegation.

test: slash invariants

---

src/contracts/core/DelegationManager.sol
src/contracts/core/DelegationManagerStorage.sol
src/contracts/interfaces/IDelegationManager.sol
src/test/integration/tests/Slashed_Eigenpod.t.sol
src/test/unit/DelegationUnit.t.sol

Naming between the `getQueuedWIthdrawal` aliases was inconsistent.
- ~made `queuedWithdrawals[withdrawalRoot]` mapping public.~
- renamed `queuedWithdrawals` -> `_queuedWithdrawals`.
- added `_queuedWithdrawals` getter
- removed previous `getQueuedWithdrawal` alias.
- renamed `getQueuedWithdrawalFromRoot` to `getQueuedWithdrawal`. 
**Result:**
Consistent function naming.

refactor: rename inconsistent `getQueuedWithdrawal` alias

---

.github/workflows/foundry.yml

The upstream repository has commented out path filtering in the foundry.yml workflow. To avoid PRs from getting blocked, we're making the same change in our branch.
* Commented out the `paths` section in the foundry.yml workflow.
**Result:**
PRs targeting `test/slashing-integration-testing` won't get blocked.

chore: comment out paths in foundry.yml workflow

---

src/test/integration/IntegrationBase.t.sol
src/test/integration/IntegrationChecks.t.sol
src/test/integration/mocks/BeaconChainMock.t.sol
src/test/integration/tests/FullySlashed_EigenPod.t.sol
src/test/integration/tests/Slashed_Eigenpod.t.sol
src/test/integration/tests/eigenpod/VerifyWC_StartCP_CompleteCP.t.sol
src/test/unit/EigenPodUnit.t.sol

We need to test full slashes for EigenPods. 
Added the `SlashType` enum which slashes either the normal amount (10 gwei), half the validators balance, or fully slashes the validator. This needs to be passed in on every call to `slashValidators`
Tests:
**Result:**
Expressive BC slashing. 
Note, delegation does not revert when the slashing factor of a staker is zero.

test: bc full and half slashes

---

.github/pull_request_template.md

We keep getting PRs that do not follow the template, that are not labeled.
- Add a warning in `pull_request_template.md` noting to use the template, and to label the PR.
**Result:**
Contributors will be prompted to properly use the template, and to label the PR.

docs: add warning in PR template

---

src/test/integration/IntegrationBase.t.sol
src/test/integration/tests/Timing.t.sol

These tests cover scenarios that specifically validate correct behavior on the cusp of a delay completing.
This PR adds test that perform a slash on the following critical timing scenarios:
* Before/after a partial/total withdrawal is no longer slashable
* Before/after an operator fully deallocates
* Before/after an operator completes deregistration from an operator set
* Before/after an operator completes an allocation
**Result:**
These timing tests ensure that the correct behavior happens on either side of critical delays

test: timing integration tests

---

src/test/integration/IntegrationBase.t.sol
src/test/integration/IntegrationChecks.t.sol
src/test/integration/tests/Deposit_Delegate_Redelegate_Complete.t.sol
src/test/integration/tests/Deposit_Delegate_Undelegate_Complete.t.sol
src/test/integration/tests/Slashed_Eigenpod.t.sol
src/test/integration/tests/SlashingWithdrawals.t.sol

On undelegation, deposit shares should be zero, there is no need to check the diff. 
Added `assert_RemovedAll_Staker_DepositShares` and updated `assert_Snap_RemovedAll_Staker_WithdrawableShares` to be non-snap. 
**Result:**
Stricter undelegate/redelegate invariants

chore: update undelegate/redelegate checks for 0 deposit shares

---

src/test/integration/IntegrationBase.t.sol
src/test/integration/IntegrationChecks.t.sol
src/test/integration/tests/BC_AVS_Slashing.t.sol
src/test/integration/tests/DualSlashing.t.sol

Tests that handle slashes by both the BC and AVS onto Native ETH. 
Added assertions for BC/AVS slashings, no full slashed included
**Result:**
Test coverage for BC/AVS edge cases. 
Need to properly bound a lot of the AVS/BC slashing cases, but this is a start

test: bc/avs slash tests

---

.github/workflows/automation.yml
.github/workflows/checks.yml

Improve developer experience by implementing consistent PR title validation. 
Before we were validating the commits in a PR, rather than the PR's title.
- Removed `commitlint` job from `.github/workflows/checks.yml`
- Added PR title validation for conventional commit format: `type: description`
**Result:**
We now enforce standardized PR titles following conventional commit format.

chore(ci): lint pr titles

---

src/test/integration/IntegrationBase.t.sol
src/test/integration/IntegrationChecks.t.sol
src/test/integration/IntegrationDeployer.t.sol

Slashable shares in queue aren't currently checked by any invariants.
- added assertion that slashable shares in queue decrease on slash if a withdrawal is queued
- added assertion that slashable shares in queue increase on queued withdrawal
- changed IntegrationDeployer to initialize starting block as nonzero to address edge cases
**Result:**
Invariant coverage for slashable shares in queue state

test: adding slashable shares in queue

---

src/test/integration/IntegrationBase.t.sol
src/test/integration/IntegrationChecks.t.sol
src/test/integration/tests/Deposit_Delegate_Allocate_Slash_Queue_Redeposit.t.sol
src/test/integration/tests/Deposit_Delegate_Redelegate_Complete.t.sol
src/test/integration/tests/upgrade/Delegate_Upgrade_Allocate.t.sol

We want to increase coverage for integration state validation.
- Added new test cases:
- `testFuzz_deposit_delegate_allocate_partialSlash_redeposit_queue_complete`
- `testFuzz_deposit_delegate_undelegate_partialSlash_complete` 
- `testFuzz_deposit_delegate_deallocate_partialSlash_queue_complete`
- `testFuzz_deposit_delegate_deregister_partialSlash_queue_complete`
- `testFuzz_delegate_zeroShares_partialSlash_deposit_undelegate_complete`
- `testFuzz_deposit_delegate_allocate_partialSlash_deallocate`
**Result:**
Move coverage.

test: more slashing state validation

---

src/test/integration/IntegrationBase.t.sol
src/test/integration/IntegrationChecks.t.sol

The staker strategy list should properly account for strategies when deposited or queued completely for withdrawal. 
Added the following checks:
- assert_StrategyNotInStakerStrategyList
- assert_StrategyInStakerStrategyList
- assert_StakerStrategyListEmpty
The first two are used on deposits or withdrawals. The last is used on undelegations. 
**Result:**
More comprehensive invariant checks

test: add invariant check for staker strategy list

---

src/test/integration/tests/SlashedOperator.t.sol

Need tests to ensure proper handling of edge cases when stakers interact with operators who have been fully slashed.
- Added new integration test file `SlashedOperator.t.sol` with three key test cases:
**Result:**
After these changes, the protocol has better test coverage for slashed operator scenarios.

test: additional slashed operator tests

---

docs/core/AVSDirectory.md

The `AVSDirectory` has been deprecated by the `AllocationManager`, as the `AllocationManager` now handles relationships between AVSs, operator sets, and operators.
Added a brief note in `AVSDirectory.md` noting its deprecation.
**Result:**
Documentation accuracy improvement!

docs(avs-directory): mark AVSDirectory as deprecated

---

src/test/integration/IntegrationBase.t.sol
src/test/integration/IntegrationChecks.t.sol
src/test/integration/tests/FullySlashed_EigenPod.t.sol
src/test/integration/tests/Slashed_Eigenpod_BC.t.sol

Additional tests on beacon chain slashing
Full slash tests:
Partial Slash Tests:
Additionally:
- Updated `_getExpectedTokenBalances` to factor in gwei rounding down for EigenPods
- Updated `queuedWithdrawal` check when delegated or undelegated 
- Got rid of unnecessary checkpointing in `SlashedEigenPod.t.sol`
**Result:**
All single beacon chain slashing state validation complete.

test: bc full slash tests and partial slash state validation

---

src/test/integration/IntegrationChecks.t.sol
src/test/integration/tests/upgrade/Complete_PreSlashing_Withdrawal.t.sol

Final upgrade tests, focusing on completing withdrawals after an operator has been slashed. 
2 tests are failing. Dependent on https://github.com/Layr-Labs/eigenlayer-contracts/pull/1176
**Result:**
Upgrade tests complete

test: remaining upgrade tests

---

src/test/integration/IntegrationBase.t.sol
src/test/integration/tests/Slashed_Eigenpod_AVS.t.sol

Address TODOs on `Slahsing_EigenPod_AVS.t.sol`
Uncomment out checks
**Result:**
Comprehensive test file

chore: address todos on fix

---

src/test/integration/IntegrationBase.t.sol
src/test/integration/IntegrationChecks.t.sol

We want to validate key invariant in our system for any share changes. 
Adds `assert_DepositShares_GTE_WithdrawableShares`
**Result:**
More comprehensive invariants

test: `depositShares` >= `withdrawableShares` invariant

---

src/test/integration/IntegrationBase.t.sol
src/test/integration/IntegrationChecks.t.sol
src/test/integration/tests/Slashed_Eigenpod_BC.t.sol

State Validation tests around slashing on beacon chain, relegating, getting slashed by an operator. 
Adds the following tests, some are failing due to the DSF inflation bug. 
Updates withdrawal as shares assertion to handle dsf rounding.
**Result:**
Beacon Chain State Validation

test: bc state validation tests

---

src/test/harnesses/EigenPodManagerWrapper.sol
src/test/integration/IntegrationBase.t.sol
src/test/integration/IntegrationChecks.t.sol
src/test/integration/IntegrationDeployer.t.sol
src/test/integration/mocks/BeaconChainMock.t.sol
src/test/integration/tests/FullySlashed_EigenPod.t.sol
src/test/integration/tests/HighDSF_Multiple_Deposits.t.sol
src/test/integration/tests/eigenpod/Register_Allocate_Slash_VerifyWC_.t.sol
src/test/integration/tests/eigenpod/SlashBC_OneBCSF.t.sol
src/test/integration/users/User.t.sol

Testing coverage for rounding edge cases.
Added test file in `Register_Allocate_Slash_VerifyWC_.t.sol`
The _init setup creates an Operator registered to an OperatorSet who gets slashed down to 1 maxMagnitude.
- Removed duplicate function `assert_Snap_StakeBecomeUnslashable`
- Added setter for BCSF on EPMWrapper
- Fixed `assert_Snap_DSF_State_WithdrawalAsShares()` for when fully slashed
- Fixed `assert_Snap_DSF_State_Delegation()` to use staker's operator magnitudes instead of staker's magnitude itself
- Additional checks helpers
- Added helper `getSlashingFactor` for User.t.sol
**Result:**
Integration Tests with 1 operator MaxMagnitude
`test_slashBC_startCompleteCP_queue_complete`
`test_slash_undelegate_redeposit` …

test: rounding tests low slashing factors

---

docs/core/RewardsCoordinator.md
src/contracts/core/RewardsCoordinator.sol
src/contracts/core/RewardsCoordinatorStorage.sol
src/contracts/interfaces/IRewardsCoordinator.sol
src/test/unit/RewardsCoordinatorUnit.t.sol

The `RewardsCoordinator` currently allows `0` duration reward submissions which leads to a divide-by-zero bug in the rewards calculation in the sidecar. 
This has already been patched in testnet and mainnet in the sidecar by ignoring any such reward submissions:
1. https://github.com/Layr-Labs/sidecar/pull/266
2. https://github.com/Layr-Labs/sidecar/pull/275
* Added validation to ensure `duration > 0` 
* Relevant tests
* Updated docs and interface natspec
**Result:**
Fixed  `EL21-01: Division By Zero In Rewards Calculation Due To Zero Duration` issue by SigmaPrime.

fix: zero duration

---

foundry.toml
src/test/integration/IntegrationBase.t.sol
src/test/integration/IntegrationChecks.t.sol
src/test/integration/tests/DualSlashing.t.sol
src/test/integration/tests/HighDSF_Multiple_Deposits.t.sol
src/test/integration/tests/Slashed_Eigenpod_AVS.t.sol
src/test/integration/tests/SlashingWithdrawals.t.sol
src/test/integration/tests/eigenpod/FullySlashed_EigenPod.t.sol
src/test/integration/tests/eigenpod/Slashed_Eigenpod_BC.t.sol
src/test/integration/tests/upgrade/Complete_PreSlashing_Withdrawal.t.sol
src/test/integration/tests/upgrade/Delegate_Upgrade_Allocate.t.sol
src/test/unit/AllocationManagerUnit.t.sol
src/test/unit/DelegationUnit.t.sol
src/test/unit/StrategyManagerUnit.t.sol
src/test/unit/mixins/SignatureUtilsUnit.t.sol

Fixing compile warnings across the repo to improve code clarity and maintainability.  
- Resolved various Solidity compile warnings.    
**Result:**  
- No more compile warnings.  
- Cleaner and more maintainable code.

fix: compile warnings + ignore non-relevant errors

---

docs/core/AllocationManager.md
docs/core/accounting/SlashingEdgeCase.md

We need to properly document when the new allocation delay is active and when undelegate dual slash edge case
- Updated `AllocationManager.md` for + 1 on `effectBlock` for `setAllocationDelay`
- Updated `SlashingEdgeCase` with undelegate applied to `Ordering of EigenPod Actions`
**Result:**
More comprehensive docs.

docs: update `effectBlock` on allocation delay; add undelegate dual slash edge case

---

docs/core/AllocationManager.md

Per and AVS builder question:
>For the slashing release, which function calls can the AVS (servicemanager) invoke to get a given Operator's currently allocated (slashable) stake amounts for a given OperatorSet?
The answer is not obvious from our current documentation and would require them to dig through our codebase to interpret the correct answer. However, this is a very important topic for AVS builders.
I've suggested the highest level possible explanation for how to get this information and where to find more information.
**Result:**
Easier opportunities for developers to self serve with this important topic.
Additional lines of markdown docs for allocationmanager.md.

docs: Explaining Minimum Slashable Stake in Better Detail

---

src/contracts/token/Eigen.sol
src/test/token/EigenWrapping.t.sol

add TokenWrapped and TokenUnwrapped events in Eigen for observability
- add TokenWrapped and TokenUnwrapped events in Eigen
- add corresponding tests
**Result:**
we can track wrapping/unwrapping actions between Eigen and BackingEigen

feat: add TokenWrapped and TokenUnwrapped events in Eigen for observability

---

.github/workflows/automation.yml

per Eigengit design, there will be special commit type as "release" to merge a release-dev branch
add 'release' as valid PR type
**Result:**
the commit that merges a release-dev branch should be of type 'release'

chore: add release label

---

.github/workflows/automation.yml

There's a small bug present in the PR title check, it does not support all characters  after the colon.
- Modified regex to support all characters. 
**Result:**
*Should* now support all characters.

feat: support all characters after colon

---

.github/workflows/foundry.yml

chain_id is currently an github secrets, but not used anywhere
remove chain id from secrets and env vars 
**Result:**
one less useless secret, no impact on ci

ci: remove chain id from secrets and env vars

---

.github/workflows/automation.yml

fork-based pr cannot use secrets or github token
disable auto labeler to prepare for enabling fork-based pr
**Result:**
auto labeler is disabled, will be potentially removed in future soon

ci: disable auto labeler to prepare for enabling fork-based pr

---

.github/workflows/rebase-release-dev-on-main.yml

rebase `release-dev/*` branches to `main` requires manual intervention. efficiency can be improved by using an automated workflow
add github action to auto rebase release-dev/* branches to main
**Result:**
a github action to auto rebase release-dev/* branches to main, runs at 8pm UTC/1pm PST

ci: add github action to auto rebase release-dev/* branches to main

---

.github/workflows/delete-unauthrized-branches.yml
README.md

enable auto delete branch upon eigengit launch
enable auto delete branch upon eigengit launch
**Result:**
in repo branch that is not `release-dev/*` or `vx.y.z` will be auto deleted upon pr creation.
fork based pr is not impacted

ci: enable auto delete branch upon eigengit launch

---

src/contracts/core/AllocationManager.sol
src/contracts/core/AllocationManagerStorage.sol
src/contracts/core/DelegationManager.sol
src/contracts/interfaces/IAllocationManager.sol
src/contracts/mixins/PermissionControllerMixin.sol
src/test/unit/AllocationManagerUnit.t.sol

Add support for redistributing slashed funds to specified recipients instead of burning them, while optimizing code size and improving test coverage.
Added a new redistribution system that allows AVSs to specify recipients for slashed funds. Code optimizations were made to reduce codesize, including consolidating repeated logic and a small `PermissionControllerMixin` refactor.
**Result:**
Slashed funds can now be redirected to specified recipients instead of being burned, with improved code efficiency and test coverage.

feat(draft): `AllocationManager` redistribution support

---

.github/workflows/validate-deployment-scripts.yml

curently there's no ci coverage for deployment scripts. scripts can be only validated manually by devs offline by running `zeus test` on terminal
pain points:
1/ no quality control of scripts that got merged in
2/ manual testing is time intensive and not scalable
i feel these pain points as i'm writing deploy scripts of elip5 (v1.6.0 release)
add a new ci workflow to auto validate deployment scripts under /scripts/release/ in all 5 envs, currently mainnet, testnet, preprod. testnet-sepolia and testnet-hoodi to be added
the ci will only run if a pr touches anything under /scripts
**Result:**
- quality control is put in place for all deployment scripts
- fully automated, to save devs time

ci: add CI to auto validate deployment scripts

---

README.md

bump deployment matrix to top of README for better readibility

docs: bump deployment matrix to top of README

---

src/contracts/core/StrategyManager.sol

the _removeDepositShares() returns a bool which is not of any meaning. simplify removeDepositShares in StrategyManager by removing that returned value
simplify _removeDepositShares() by removing returned extra bool
**Result:**
_removeDepositShares() is simplified and binary size is reduced

feat: simplify removeDepositShares in StrategyManager

---

.github/workflows/validate-deployment-scripts.yml
script/releases/Env.sol
script/releases/v1.4.1-slashing/3-executeUpgrade.s.sol

add testnet envs sepolia and hoodi to validate-deployment-scripts, since both are deployed correctly now
**Modification:**
- add API `Env.env()` to expose zeus env to scripts
- change v1.4.1 script to skip EPM assertion on testnet-sepolia
- add testnet envs sepolia and hoodi to validate-deployment-scripts, since both are deployed correctly now

ci: add testnet envs sepolia and hoodi to validate-deployment-scripts

---

CHANGELOG/CHANGELOG-1.5.0.md
CHANGELOG/CHANGELOG-1.6.0.md
CHANGELOG/CHANGELOG-1.7.0.md
CHANGELOG/CHANGELOG-template.md
MAINTENANCE.md

improve our release management and legibility
- add CHANGLOG structure and template
- add prefilled CHANGELOG for upcoming 3 releases

docs: add templates for changelog and release notes

---

src/contracts/core/AllocationManager.sol
src/contracts/core/SlashEscrowFactory.sol
src/contracts/core/SlashEscrowFactoryStorage.sol
src/contracts/mixins/Deprecated_OwnableUpgradeable.sol
src/test/unit/AllocationManagerUnit.t.sol
src/test/unit/SlashEscrowFactoryUnit.t.sol

We want to resolve any review issues that arise.
- Use larger of strategy or global delay: @non-fungible-nelson 
- Fix storage overrides noted from `Deprecated_OwnableUpgradeable` @wadealexc 
- Use `EnumerableSet` instead of `EnumerableSetUpgradaeable` since it doesn't contain storage
- Add missing event in `initialize()`.
- Prevent `address(0)` during `createRedistributableOperatorSets` for event sanitation.
- Improve check legibility @wadealexc 
**Result:**
Current review concerns have been addressed.

fix: review issues

---

src/contracts/core/AllocationManager.sol
src/contracts/core/DelegationManager.sol
src/contracts/interfaces/IDelegationManager.sol
src/test/mocks/DelegationManagerMock.sol
src/test/unit/DelegationUnit.t.sol

We want to minimize the diff between slashing and redistribution. Bring back the single call from ALM to DM for slashes. 
Bring back single call from ALM to DM for slash, instead of aggregating all mags. 
**Result:**
Smaller Diff

chore: bring back non-arrayified slashOperatorShares

---

.github/configs/storage-diff.json
src/contracts/mixins/Deprecated_OwnableUpgradeable.sol

Storage checker didn't have ALM added. Also we needed to fix the deprecated ownable mixing. 
Fix mixing to inherit from `ContextUpgradeable`. Add ALM to storage-diff.json. 
**Result:**
Correct storage checks.

fix: storage checker

---

src/contracts/core/SlashEscrowFactory.sol
src/contracts/interfaces/ISlashEscrowFactory.sol
src/test/unit/AllocationManagerUnit.t.sol
src/test/unit/SlashEscrowFactoryUnit.t.sol

We want to ensure we have full coverage unit tests for `SlashEscrowFactory` and `SlashEscrow` in preparation for audits.
- Adds checks for all view methods.
**Result:**
Brings coverage up to 100% for all branches/fns/etc.

test: full coverage `SlashEscrowFactory` + `SlashEscrow`

---

src/contracts/core/StrategyManager.sol
src/contracts/interfaces/IStrategyManager.sol
src/test/mocks/SlashEscrowFactoryMock.sol
src/test/unit/StrategyManagerUnit.t.sol

Currently, there's a bug in the `SM` where if you loop through the burnable shares queue, you may not clear all due to swap and pop of an Enumerable Map. Furthermore, we also are constrained by a token transfer taking too much gas and blocking transfer out of funds. 
- Iterate backwards on `decreaseBurnOrRedistributableShares ` 
- Overloaded `decreaseBurnableShares` with a version to pass in an index. This function will escrow a single share (called by above too). Now, we do not need a max strategy per opSet requirement
- Unit tests for both `increaseBurnOrRedistributableShares` and `decreaseBurnOrRedistributableShares`
- Added the following introspection:
-- `getBurnOrRedistributableShares(operatorSet, slashId) returns (Strategy[] Strats, uint256[] …

fix: enumerable map overwrite

---

src/contracts/core/SlashEscrowFactory.sol
src/contracts/interfaces/ISlashEscrowFactory.sol
src/test/unit/AllocationManagerUnit.t.sol
src/test/unit/SlashEscrowFactoryUnit.t.sol

For clarity, let's deploy the `SlashEscrow` in `initiateEscrow`.
1. In `initiateEscrow `, deploy the `SlashEscrow` if it hasn't been deployed
2. Also add the startBlock, opSet to pending, and slashId to pending in this if block
**Result:**
No more counterfactual. Less redundant updates for multiple strategies in a slashID.

feat: deploy escrow in `initiateSlashEscrow`

---

.gitattributes

To enable Certora `.spec`/`.conf` highlighting as described in their [documentation](https://docs.certora.com/en/latest/docs/user-guide/github_highlighting.html).
Two additional lines added to `.gitattributes`
**Result:**
Better `.spec`/`.conf` highlighting within GitHub for ease of use

chore: update .gitattributes with Certora .spec/.conf formatting

---

src/contracts/core/StrategyManager.sol

Small optimization found.
Checks whether a strategy has already been added via .set() return value rather than a separate .contains() check.
**Result:**
More optimal code.

perf: avoid binary search

---

.github/workflows/foundry.yml
src/contracts/core/StrategyManager.sol
src/contracts/interfaces/ISlashEscrowFactory.sol
src/test/integration/IntegrationBase.t.sol
src/test/integration/IntegrationChecks.t.sol
src/test/integration/IntegrationDeployer.t.sol
src/test/integration/tests/Deposit_Delegate_Allocate_Slash_Escrow.t.sol
src/test/integration/tests/Deposit_Delegate_Allocate_Slash_Queue_Redeposit.t.sol
src/test/integration/tests/DualSlashing.t.sol
src/test/integration/tests/FullySlashed_Operator.t.sol
src/test/integration/tests/HighDSF_Multiple_Deposits.t.sol
src/test/integration/tests/Slashed_Eigenpod_AVS.t.sol
src/test/integration/tests/SlashingWithdrawals.t.sol
src/test/integration/tests/Timing.t.sol
src/test/integration/tests/eigenpod/Register_Allocate_Slash_VerifyWC_.t.sol
src/test/integration/tests/eigenpod/SlashBC_OneBCSF.t.sol
src/test/integration/tests/eigenpod/Slashed_Eigenpod_BC.t.sol
src/test/integration/tests/upgrade/Complete_PreSlashing_Withdrawal.t.sol
src/test/integration/users/AVS.t.sol
src/test/utils/ArrayLib.sol

We want integration test coverage for the redistribution relaese.
- Fixed view revert bug (see comment bellow).
- Added timing tests (cannot release escrow before delay, can after)
**Result:**
Integration test coverage.

test: redistribution integration

---

CHANGELOG/CHANGELOG-1.5.0.md

Changelog for redistribution 
Update `CHANGELOG-1.5.0.md`
**Result:**
Documented release notes.

docs: redistribution changelog

---

CHANGELOG/CHANGELOG-1.6.0.md

feat: add changelog and update release notes of v1.6.0
add changelog and update release notes of v1.6.0
**Result:**
add changelog and update release notes of v1.6.0

feat: add changelog and update release notes of v1.6.0

---

script/utils/ExistingDeploymentParser.sol
src/contracts/interfaces/IKeyRegistrar.sol
src/contracts/multichain/BN254TableCalculator.sol
src/test/integration/IntegrationBase.t.sol
src/test/integration/IntegrationDeployer.t.sol
src/test/integration/tests/multichain/BN254OperatorSet_CalculateWeights.t.sol
src/test/integration/users/AVS.t.sol
src/test/integration/users/User.t.sol
src/test/unit/BN254TableCalculatorUnit.t.sol

Testing for https://github.com/Layr-Labs/eigenlayer-contracts/pull/1429 
Updates Integration test framework for testing the BN254OperatorTableCalculator 
Contracts
- Updated `BN254TableCalculator` to have LOOKAHEAD_BLOCKS be immutable
Tests
- Updated Users (AVS.t.sol, User.t.sol)
- IntegrationBase
- `_newRandomAVS_WithBN254`
- `_newRandomAVS_WithECDSA`
- IntegrationDeployer, added multichain contracts although some are missing pending feat PRs to be merged. 
- ExistingDeploymentParser, added contract addresses
**Result:**
- Updated Integration test framework for testing the BN254OperatorTableCalculator and other multichain flows
- fuzz tests for BN254OperatorTableCalculator in `BN254OperatorSet_CalculateWeights.t.sol`

test: integration tests for op table calculator

---

docs/core/SlashEscrowFactory.md
src/contracts/core/SlashEscrowFactory.sol
src/contracts/core/SlashEscrowFactoryStorage.sol
src/contracts/interfaces/ISlashEscrowFactory.sol
src/test/integration/IntegrationBase.t.sol
src/test/integration/IntegrationChecks.t.sol
src/test/unit/SlashEscrowFactoryUnit.t.sol

Previously, we stored `startBlock` and computed the `completeBlock` at runtime by iterating through the list of added strategies for a given `slashId`. This approach required recalculating the `completeBlock` each time.
We now store `completeBlock` directly instead of `startBlock`. During each call to `initiateSlashEscrow`, we compare the delay of the newly added strategy to the current `completeBlock` for the `slashId`. If the new delay is larger, we update `completeBlock` accordingly. This ensures that the maximum delay is always preserved.
**Result:**
The `completeBlock` for each `slashId` is now computed and maintained incrementally, eliminating the need for runtime iteration over all strategies.

fix(audit): out-of-gas issue

---

docs/core/SlashEscrowFactory.md
src/contracts/core/SlashEscrowFactory.sol
src/contracts/interfaces/ISlashEscrowFactory.sol
src/test/unit/SlashEscrowFactoryUnit.t.sol

We want to make `releaseSlashEscrow` and `releaseSlashEscrowByStrategy` permissionless.
- Removed `onlyRedistributionRecipient` check.
**Result:**
Escrow can be released by anyone.

refactor: remove only redistribution recipient check

---

docs/core/SlashEscrowFactory.md
src/contracts/interfaces/ISlashEscrowFactory.sol

Missing documentation noting that an upgrade is required to rescue paused funds.
- Update `ISlashEscrowFactory.sol` and `SlashEscrowFactory.md`.
**Result:**
L-01 resolved.

docs(audit): note upgrade rescue flow

---

src/contracts/interfaces/IECDSACertificateVerifier.sol
src/contracts/multichain/ECDSACertificateVerifier.sol

feat: ecdsacv views

---

README.md

Sepolia is on `v1.6.0-rc.0`
Update ReadMe
**Result:**
Up to date version matrix

docs: update version matrix

---

script/initialize-operator-set/DeployReleaseManager.s.sol
script/utils/CrosschainDeployLib.sol

feat: multichain deployments

---

src/test/integration/IntegrationDeployer.t.sol
src/test/unit/BN254CertificateVerifierUnit.t.sol
src/test/unit/OperatorTableUpdaterUnit.t.sol

Test should be passing.
- Minor (likely rebase) error fixes.
**Result:**
Tests passing.

test(redistribution-changes): passing

---

docs/permissions/KeyRegistrar.md
src/contracts/interfaces/IKeyRegistrar.sol
src/contracts/permissions/KeyRegistrar.sol
src/contracts/permissions/KeyRegistrarStorage.sol
src/test/unit/KeyRegistrarUnit.t.sol

We want to get the operator address from signing key 
- Adds storage for `_keyHashToOperator`
- Adds a `getOperatorFromSigningKey` view func. Pass in the operatorSet and keyData, which is either the signing key for ECDSA or G1/G1+G2 key for BN254
**Result:**
Cleaner API

feat: key data reverse lookup 

---

docs/multichain/destination/CertificateVerifier.md
docs/multichain/source/CrossChainRegistry.md
script/releases/v1.7.0-multichain/1-deploySourceChain.s.sol
src/contracts/interfaces/ICrossChainRegistry.sol
src/contracts/multichain/CrossChainRegistry.sol
src/contracts/multichain/CrossChainRegistryStorage.sol
src/test/integration/MultichainIntegrationBase.t.sol
src/test/tree/CrossChainRegistry.tree
src/test/unit/CrossChainRegistryUnit.t.sol

We should be preventing an invalid staleness period from being set by an operatorSet. A staleness period is invalid if it is less than the cadence at which tables are updated. 
- Add requirement to `minimumStalenessPeriod` in `CrossChainRegistry`
- Prevent staleness periods less than `tableUpdateCadence`
- Add setter for `tableUpdateCadence`
- Update docs
**Result:**
Less likelihood for footguns by devs

feat: invalid staleness period prevention

---

src/contracts/multichain/CrossChainRegistryStorage.sol

Chore: fix storage gap in CCR. Vars take up 8 slots total
Update storage gap to be size 42
**Result:**
Correct gap

fix: storage gap in `CrossChainRegistry`

---

src/test/mocks/MockBN254CertificateVerifier.sol
src/test/mocks/MockBN254CertificateVerifierFailure.sol
src/test/mocks/MockECDSACertificateVerifier.sol
src/test/mocks/MockECDSACertificateVerifierFailure.sol

We needed to fix the build as a result of the rebase. There were some new functions added to the Certificate verifier interfaces which need to be reflected in the Mocks.
Updated Mock certificate verifiers
**Result:**
Successful build

fix: mock certificate verifiers

---

docs/multichain/destination/CertificateVerifier.md
docs/multichain/destination/OperatorTableUpdater.md
script/releases/v1.7.0-multichain/4-instantiateDestinationChainProxies.s.sol
src/contracts/interfaces/IOperatorTableUpdater.sol
src/contracts/multichain/OperatorTableUpdater.sol
src/test/unit/OperatorTableUpdaterUnit.t.sol

Currently, for new destination chain deployments, the following vulnerability exists:
1. We post an certificate with an invalid global table root
2. The root is invalidated
3. We start up a new chain
4. That invalid certificate is replayed on the new chain
5. AVS is exploited somehow
We need to prevent previous certificates from being replayed
In the initialize function of `OperatorTableUpdater`, set the `_latestReferenceTimestamp` to the `block.timestamp`
**Result:**
Preventing replay of past global roots on new deployments

fix: prevent `globalTableRoot` certificate replay upon newly instantiated CertificateVerifiers/OperatorTables

---

foundry.toml

Foundry will be adding `forge lint` to stable soon, I want to support `forge lint` config beforehand. 
- Added `forge lint` related config to `Foundry.toml`.
- Disabled linting for `script` and `src/test`.
**Result:**
Can configure `forge lint`.

chore: update `foundry.toml` to include `forge lint` config

---

docs/core/libraries/Merkle.md
src/contracts/libraries/Merkle.sol
src/test/unit/BN254CertificateVerifierUnit.t.sol
src/test/unit/OperatorTableUpdaterUnit.t.sol

As part of an audit for the Merkle library, several low and informational findings were found. This PR consolidates all informational findings to fix, as well as additional commits for findings discovered along the way, with a specific commit for each finding.
All Lows are separated into individual PRs into the [release-dev/merkle-audit-fixes](https://github.com/Layr-Labs/eigenlayer-contracts/tree/release-dev/merkle-audit-fixes) branch
* Completely uplifted natspec, matching current EigenLayer quality and standards
* Four new error codes:
* `InvalidIndex` for indices outside of the Merkle tree's max index
* `LeavesNotPowerOfTwo` for leaves (particularly for SHA256 functions) that don't match the expected length condition
* `NoLeaves` for an empty …

fix(audit): Merkle library infos

---

pkg/bindings/ComputeRegistry/binding.go
pkg/bindings/ComputeRegistryStorage/binding.go
pkg/bindings/IComputeRegistry/binding.go
src/contracts/cloud/ComputeRegistry.sol
src/contracts/cloud/ComputeRegistryStorage.sol
src/contracts/interfaces/IComputeRegistry.sol
src/test/mocks/CrossChainRegistryMock.sol
src/test/mocks/KeyRegistrarMock.sol
src/test/mocks/ReleaseManagerMock.sol
src/test/unit/ComputeRegistryUnit.t.sol

We need a ComputeRegistry for AVSs to register their operator set to  EigenCompute so that the EigenCompute operator can register that to that AVS operator set and pull the latest release from ReleaseManager.
Additionally the AVS needs to sign a Terms of Service before they can register for EigenCompute
https://lucid.app/lucidchart/26f35348-cd23-47d4-b848-0f4f9335c719/edit?invitationId=inv_8dc26eb0-772d-4018-884f-f54d46d3ee0f&page=0_0#
* ComputeRegistry core contract, interface and storage. 
* Terms of Service is signed through a EIP-712 signature.
* Unit tests.
* Updated Bindings
**Result:**
ComputeRegistry

feat: compute registry

---

src/contracts/avs/task/TaskMailbox.sol
src/contracts/interfaces/ITaskMailbox.sol
src/test/unit/TaskMailboxUnit.t.sol

Fixing a bug where a random actor could permissionlessly call `TaskMailbox::submitResult` with an old cert+result combination (as long as the cert is not stale) but for a completely different task directed at the same operator set in the TaskMailbox. This could lead to DoS of the taskCreator. 
The `messageHash` of the cert now is `keccak256(abi.encode(taskHash, result))` instead of just `keccak256(result)`. This ensures that the messageHash is applicable only for a specific task and can't be replayed across tasks.
**Result:**
Fixes `SigmaPrime: ELHG-02` finding.

fix: task replay directed at same operator set

---

script/releases/v1.8.1-hourglass-testnet-replay-fix/1-deployTaskMailboxImpl.s.sol
script/releases/v1.8.1-hourglass-testnet-replay-fix/2-queueTaskMailboxUpgrade.s.sol
script/releases/v1.8.1-hourglass-testnet-replay-fix/3-executeTaskMailboxUpgrade.s.sol
script/releases/v1.8.1-hourglass-testnet-replay-fix/upgrade.json

Zeus scripts for `v1.8.1` of the protocol that handles the task replay fix in the TaskMailbox. 
New release `v1.8.1` for `preprod`, `testnet-sepolia` and `testnet-base-sepolia`
**Result:**
Testnet fix ready

chore: zeus script for task replay fix

---

foundry.toml
script/utils/ExistingDeploymentParser.sol
src/contracts/core/AllocationManager.sol
src/contracts/mixins/SplitContractMixin.sol

Due to our proxy pattern with split contracts (separate view/storage/main contracts), Etherscan only displays the functions directly in the main contract when users visit its address. This means view functions defined in separate view contracts are not visible or easily accessible on Etherscan, making it difficult for users to query protocol state.
- Added "ghost funcitons" in `AllocationManager`
**Result:**
`AllocationManager` once agian supports Etherscan for view functions.

feat: explore ghost fns
